### ISSUE TITLE
ostream-new is available by default? (rholangweb security issue)

### ISSUE THREAD

**Issue by dckc** [rchain/rchain#162]
The `log_time.rho` example includes `ostream-new("test.txt")`. In the context of the web front end, this actually creates new files.

Where should this be addressed? In rosette? Or somehow in the deployment of the web front end?

cc @MParlikar

**Comment by MParlikar** [comment]
[RHOL-76](https://rchain.atlassian.net/browse/RHOL-76)  has been created.  It is preferable that the Web front end address the cleanup of files if possible.

**Comment by dckc** [comment]
There's also [RHOL-78](https://rchain.atlassian.net/browse/RHOL-78). Let's track things there.
