### ISSUE TITLE
"n-1" is parsed as QVar rather than QMinus rule.

### ISSUE THREAD

**Issue by AbnerZheng** [rchain/rchain#165]
If you type "n - 1" ( with space before or behind '-'), then you will get the right rule `QMinus` applyed. So there is something wrong with  rule  Var.
I wander if there any need for a variable name such as "xxx-xxx" being valid.

**Comment by MParlikar** [comment]
@guardbotmk3 please weigh in.  If this is an issue, we will file a Jira issue.

**Comment by nashef** [comment]
In lisps, `foo-bar` is a valid identifier, but `x - 3` is not a valid expression. In lisp, you write `(- x 3)` and there is no ambiguity. Please choose one or the other, but don't try to mix both.

**Comment by echatav** [comment]
resolved by #170
