### ISSUE TITLE
Hello sir !!!

### ISSUE THREAD

**Issue by raja-rizki** [rchain/rchain#270]
I want to ask sir, if in this project provide the translation file, I want to participate, thanks

**Comment by kirkwood** [comment]
We are interested in having translations of documents like the one you prepared. Have you read through the documentation for contributors?
 * [Members/CONTRIBUTING.md](https://github.com/rchain/Members/blob/6824f4733df4381f665852109c9f8aece9167f96/CONTRIBUTING.md) (for most contributions)
 * [rchain/CONTRIBUTING.md](https://github.com/rchain/rchain/blob/master/CONTRIBUTING.md) (specific to more technical contributions)

[Becoming a co-op member](https://github.com/rchain/Members/blob/6824f4733df4381f665852109c9f8aece9167f96/CONTRIBUTING.md#becoming-a-member) will also make it possible for you to be compensated for your efforts.

Finally, whatever you do, [join the public RChain Discord](https://discord.gg/fvY8qhx), if you haven't already done so.

**Comment by raja-rizki** [comment]
No, thank you :)
