### ISSUE TITLE
PoS rewards state contains negative values (main net)

### ISSUE THREAD

**Issue by tgrospic** [rchain/rchain#2956]
## Overview

Fix is in progress planned for Hard Fork 2:
- #3514

Current main net data for rewards and bonds saved in Proof Of Stake contract. Rewards are from PoS "committed" values transferred from pending map which is updated in each block.

The transfer is done on each epoch change or on slashing event. On main net epoch change did not happen yet so transfer must happen when one node is slashed.

| Validator               | Stake           | Rewards
|-------------------------|-----------------|-------------------
| 04f026cc75...baf0f37ba3 | 150500000000000 | 11462327
| 041cd20e39...36d465c257 | 100000000000000 | -9528404
| 04ab96784c...48fadde862 | 100000000000000 | -9528404
| 0422ae069d...0368f274c5 | 100250000000000 | -9422609
| 04fb67c987...eb32061d64 | 151000000000000 | 11703106
| 0454405456...1d1a74007d | 100000000000000 | -9528404
| 04ce255756...51d3503d53 | 150500000000000 | 11462327
| 04a9413db3...2ebea5cb93 | 151000000000000 | 11703106
| 04bfc03c72...cb8a0bf138 | 0               | 0
| 0404adf3da...20a9e94881 | 150000000000000 | 11161644

Rholang code to get this data from PoS.
```scala
new return, posCh, rewardsCh, lookup(\`rho:registry:lookup\`) in {
  lookup!(\`rho:rchain:pos\`, *posCh) |
  for (@(_, pos) <- posCh) {
    @pos!("getRewards", *rewardsCh) |
    //@pos!("getBonds", *rewardsCh) |

    for (@rewards <- rewardsCh) {
      return!(("PoS rewards", rewards))
    }
  }
}
```

**Comment by zsluedem** [comment]
I checked this deploy in test net. But I don't see rewards like that.

| Validator               | Stake           | Rewards
|-------------------------|-----------------|-------------------
| 0466fe01872364f0f26be... | 10000032 | 457599852
|0468253959709c06610a... | 10000004 | 457598341
|04953bfb7421d530712c... | 10000002 | 457598256
|04bcca4904285db7585e... | 10000008 | 457598504
|04abd47e88392bc5edcd... | 0 | 457598504

**Comment by tgrospic** [comment]
@zsluedem is this with slashing block?

**Comment by zsluedem** [comment]
nope

**Comment by zsluedem** [comment]
> @zsluedem is this with slashing block?

no. Maybe after https://github.com/rchain/rchain/pull/2967 is merged, we can find out which block mess up with that.

**Comment by zsluedem** [comment]
We know what is the problem now. It is a Long overflow problem.

> $(sbt console) 150000000000000L * 109363L / 1500000000000000L = -1361

it happened in https://github.com/rchain/rchain/blob/dev/casper/src/main/resources/PoS.rhox#L774.

**Comment by dckc** [comment]
@tgrospic I got the impression from our discussion that you expect this to be addressed in milestone 9 , so I put it there . If that's not right, if the the stuff in milestone 9 only part of addressing this, please adjust.

**Comment by wangjia184** [comment]
What is supposed to do to fix this issue?   When arithmetic overflow occurs, terminate the reduction? or raise recoverable error which can be caught by user-code ?  The latter seems not easy since I dont see error handling in rholang.

**Comment by zsluedem** [comment]
> What is supposed to do to fix this issue? When arithmetic overflow occurs, terminate the reduction? or raise recoverable error which can be caught by user-code ? The latter seems not easy since I dont see error handling in rholang.

https://github.com/rchain/rchain/issues/3369#issuecomment-813794140

**Comment by tgrospic** [comment]
This bug is resolved in PR with changes to PoS:
- #3559

More info in related issues:
- #3514
- #3513
