### ISSUE TITLE
Investigate a good way to generate api document.

### ISSUE THREAD

**Issue by zsluedem** [rchain/rchain#2974]
### If this relates to existing RChain documentation, please provide the complete, specific URL and location in the page
No.

### Please describe the problem including, missing, unclear or incorrect documentation
Currently, we have very poor API documentations which would confuse normal developers. We need to investigate ways to 

### Please provide the improvement suggestion, including links to any reference material and examples
[OpenAPI](https://swagger.io/specification/) is one of the tools we can choose.

**Comment by nzpr** [comment]
OpenAPI is for RESTful only. There are ways to convert gRPC to OpenAPI, I tried to do this here https://rchain-community.readme.io/reference#deployservice. But it's not very good looking. In general documenting GRPC interfaces is not very handy. It's supposed that developer just use generated code as an API reference I believe.

But indeed, we need good API reference.

**Comment by zsluedem** [comment]
@nzpr https://rchain-community.readme.io/reference#deployservice This looks good. I just found out.

**Comment by tgrospic** [comment]
We have protobuf definition files so from that client code can be generated. This is also exposed with gRPC reflection as API schema. https://github.com/rchain/rchain/pull/2698

What we need is similar thing for Web API. OpenAPI can provide this functionality. So the question is how to generate this specification from Scala code.

We are using http4s lib to define HTTP routes which is the main part for schema with input/output types.
https://github.com/rchain/rchain/blob/7c535f00e6bc5e47634b93300b08a7f140dba87a/node/src/main/scala/coop/rchain/node/web/WebApiRoutes.scala#L123-L127

Maybe Rho :smile: would be nice to use. It can generate OpenAPI (ex Swagger) specification.
https://github.com/http4s/rho#ρ-a-dsl-for-building-http-services-with-http4s

Caliban looks interesting to generate GraphQL schema.
https://ghostdogpr.github.io/caliban/docs/#a-simple-example
_Supports custom effect type for resolvers and http4s but internally uses ZIO._

---

The more general idea is that we have one Scala API and just generate different protocol specifications which can be used with different transport layers. There is no reason why we cannot have protobuf over HTTP or JSON over gRPC.

**Comment by dckc** [comment]
Has https://github.com/rchain/rchain/tree/dev/docs/rnode-api been completely forgotten? it has an index.md generated from the .proto files and a Makefile that shows how it's done.

Much of the stuff in the .proto files lacks docstrings, but I put some effort into documenting `DeployService`:
https://github.com/rchain/rchain/blob/dev/docs/rnode-api/index.md#deployservice

**Comment by dckc** [comment]
Since I [first worked with scala](https://www.madmode.com/2010/advogato_entry0071.html) in 2010, it has bugged me that doctest is not a community norm; that is: that effort spent on tests isn't easily re-used in generating documentation. It's a norm in the python and rust worlds (and it's supported in js and go and haskell, IIRC) but it's nowhere in the scala world.

[WebApiRoutesTest.scala](https://github.com/rchain/rchain/blob/dev/node/src/test/scala/coop/rchain/node/web/WebApiRoutesTest.scala) has a rich collection of examples. They're not written at the HTTP-on-the-wire level (or curl / php / py / js) level like in most Web API docs, but they could / should be:

```
"GET getBlock" should "detailed block info"
"GET getBlocks" should "return a list of LightBlockInfo"
"GET getApiStatus" should "return api status"
"GET prepareDeploy" should "return latest block number info"
"POST prepareDeploy" should "return latest block number info"
...
```

**Comment by tgrospic** [comment]
@dckc Nice, I was not aware of your generator from proto to Markdown. We should include it as part of other generators for API and documentation.

The plan is that we move towards unified definition for API with all necessary information to generate different protocols (runtime and types) with documentation and examples.

Unfortunately _WebApiRoutesTest_ is not very useful, it's basically tests _circe_ JSON encoder using WebApi interface. @zsluedem created PR to remove it #2984. But this is just intermediate step, we still need to specify and test our JSON format.

**Comment by zsluedem** [comment]
https://github.com/http4s/rho found a good tool to generate swagger

**Comment by dckc** [comment]
I got started on a swagger definition:

https://github.com/rchain-community/liquid-democracy/blob/dev-tools/rclient/rnode.yaml 71d2f9d https://github.com/rholang/rholang.github.io/pull/20

try it out in https://petstore.swagger.io/ 

I went over it with @jimscarver and we made a [recording](https://www.youtube.com/watch?v=IdPKQ76NP_w)

**Comment by dckc** [comment]
@zsluedem #3128 looks very interesting... can it include example inputs and outputs? Those are very important. Prose documentation as well.

I wonder if it's better to keep the api definition in https://github.com/rchain/rchain/tree/dev/docs/ (perhaps /docs/rnode-api ) and _test_ that it's consistent with the scala code rather than generating it with scala code. It seems important to be able ship the api definition independent of the rest of rnode; for example in an npm package or the like.

**Comment by zsluedem** [comment]
[swagger.zip](https://github.com/rchain/rchain/files/5229075/swagger.zip)

This is what #3128 generate on the `swagger.json`. We can use that directly now. The pr still needs some work on error handling.

**Comment by dckc** [comment]
the RhoExpr stuff in that generated swagger.json looks wrong. We get back `{ ExprString: { data: "abc" }}`, not `{ type: "ExprString", data: "abc" }`

**Comment by dckc** [comment]
FYI, the swagger stuff is now live at https://developer.rchain.coop/rnode-api

https://github.com/rchain/developer.rchain.coop/pull/3

**Comment by zsluedem** [comment]
create a new issue to address this.
