### ISSUE TITLE
rnode fails on java options starting with -X

### ISSUE THREAD

**Issue by gsj5** [rchain/rchain#3007]
Adding `-Xlog:gc*` option to docker-compose startup fails with error "[rchain] Error: Unknown option 'X'" but `java  -Xlog:gc*` works as expected in latest rnode release, aka 0.9.25.1.

**Comment by nzpr** [comment]
@gsj5 is this issue still relevant? Did `-J-Xlog:gc*`work?

**Comment by gsj5** [comment]
Thanks!
