### ISSUE TITLE
Scala Steward response

### ISSUE THREAD

**Issue by 9rb** [rchain/rchain#3010]
https://github.com/scala-steward-org/repos/pull/403

I tried to activate Scala Steward and this is what they say

"This repo was here before and had been removed in 8e599c8. Should it really be added again now?"  This was related request by Artur back in 2018 Nov to remove it "Remove rchain/rchain

Thx for the great tool! Unfortunately, because of specifics of our dev process, using it so far comes with too much overhead. This could be easily fixed though by having: - all commits form the Steward being signed with a gpg key - all lib updates being put in a single PR, with a separate commit …"

What's our response? @tgrospic Should we perhaps run it on a branch first and see if it makes sense to have it on the main repo?

**Comment by tgrospic** [comment]
One thing seems resolved, commits are now signed https://github.com/rchain/rchain/pull/1880#issuecomment-440055748.

The second point seems like inconvenience if all lib updates are in one commit inside PR but I don't see it as a stopper.

**Comment by 9rb** [comment]
Scala Steward PR is merged. We should expect to get some PRs from there
