### ISSUE TITLE
SafetyOracle does not work properly with bonding

### ISSUE THREAD

**Issue by nzpr** [rchain/rchain#3058]
## Overview
We ave two questionable thing with SafetyOracle
1) It uses main parent bonds map -> suggestion is to use bonds map of the block itself (per postStateHash of block). Might require investigating if we have access to that data/
2) It takes into account all records from the bonds map -> it has to use only active validators

### Impact
This method is a subject <https://github.com/rchain/rchain/blob/8fb7bc466ea9a7b516133da40b85da95d11595bb/casper/src/main/scala/coop/rchain/casper/SafetyOracle.scala#L114-L118>

We should change this as a part of shard config

UPD.
We need

1) Not add latest message for any validator until message is created. Bonding should not lead to LM creation. (TODO discuss)
2) Use bonds map of message itself and not main parent bonds map (TODO discuss)
3) Check if only active validators are used

**Comment by nzpr** [comment]
Another reference for this issue https://github.com/rchain/rchain/pull/3366#issuecomment-823234880

**Comment by nzpr** [comment]
We need
1) Not add latest message for any validator until message is created. Bonding should not lead to LM creation. (TODO discuss)
2) Use bonds map of message itself and not main parent bonds map (TODO discuss)
3) Check if only active validators are used

**Comment by tgrospic** [comment]
@nzpr Is this still relevant?

**Comment by nzpr** [comment]
No, we won't have main parent so not relevant, let me close.
