### ISSUE TITLE
Fork-choice tip calculation grows linearly

### ISSUE THREAD

**Issue by nzpr** [rchain/rchain#3094]
After epoch change we have latest message from non active validators participating in calculation of FCT. This leads to increasing of FCT calculation time, because DAG height on which this calculation is being performed grows as network proceeds.

This code slows down 
https://github.com/rchain/rchain/blob/27787e1f47392e1998135db2316c2c32651abf4d/casper/src/main/scala/coop/rchain/casper/Estimator.scala#L51-L72
<img width="274" alt="Screenshot 2020-08-22 at 13 55 27" src="https://user-images.githubusercontent.com/1746367/90954686-26228f00-e47f-11ea-8973-a9ac7787cfb9.png">

On testnet this code takes milliseconds.

**Comment by 9rb** [comment]
https://java2blog.com/lca-k-ary-tree-osqrtheight/
