### ISSUE TITLE
Enable parallel execution of non-conflicting deploys

### ISSUE THREAD

**Issue by nzpr** [rchain/rchain#3096]
## Overview
This is the first step for block merge.
It includes 
- refactoring of RuntimeManager so it acts as a Runtime producer that node can use to execute some rholang code.
- making cost-accounting work with such Runtimes.

**Comment by tgrospic** [comment]
@nzpr Is this completed as part of #3299?

**Comment by nzpr** [comment]
@tgrospic it should be autoclosed, but it did not work. So I'm closing
