### ISSUE TITLE
E.join is not a function getting value off chain

### ISSUE THREAD

**Issue by jimscarver** [rchain/rchain#3125]
### What did you expect to see?
value of data stored on testnet at `rho:id:ar17ohqq83kx7a16nbfquwu9gxidduk9hstgbs9gkbj63o8gqyh1ye`
### What did you see instead?
![image](https://user-images.githubusercontent.com/3037201/92983682-fb6e9980-f472-11ea-8f7e-ca028ead6e1b.png)
### Steps to reproduce the bug
deploy
```scala
new return(`rho:rchain:deployId`),
  lookup(`rho:registry:lookup`)
in {
  new valueCh in {
    // Fill in registry URI: `rho:id:11fhnau8j3...h4459w9bpus6oi`
    lookup!( `rho:id:ar17ohqq83kx7a16nbfquwu9gxidduk9hstgbs9gkbj63o8gqyh1ye` , *valueCh) |
    for (@value <- valueCh) {
      return!(value)
    }
  }
}
```

### What version of RNode are you using?
RChain Node 0.9.25.4 (41a42a330143e2451097cefa36b9b733b989b4f4)
### What is your environment?
https://tgrospic.github.io/rnode-client-js/

**Comment by jimscarver** [comment]
The expected value was:
```js
{
      "Board: WEC": {
        "noAddr": "11112aoa6NLYomYZro566XZVGEXyCDqeqDcp8Pzg81Ckuws6SexC99",
        "shortDesc": "Wile E. Coyote for Board Member",
        "yesAddr": "11112gUFvJR6JBDYJURETaWUBpEDa1EyjgRHFncEfQ4hGECnciPnhw"
      },
      "Board: DaD": {
        "noAddr": "11112Cwtg2Bs4WUAYrXhL9xZXXSXr9Gn62Cty39RhUaBnqjrKkqwAZ",
        "shortDesc": "Daffy Duck for Board Member",
        "yesAddr": "1111TnFUN7eZBWXp3QQACQRRxpcS5uH5Bpf67vikWhA5e3F6ikAmU"
      },
      "Member Swag": {
        "docLink": "https://docs.google.com/docs/SWAG.doc",
        "noAddr": "11112uGayGEi57D44Drq3V4iw5WWyfXbcVvsDangRTE7TaR3J4U4FD",
        "shortDesc": "The Item of Business I want to propose is to provide all new members with stickers and t-shirts with the RChain logo on it as part of their membership onboarding package.",
        "yesAddr": "11112i8bYVDYcm4MSbY3d1As28uY151xoMS7AyiTvZ2YmNJ8Nw13v9"
      },
      "Board: DoD": {
        "noAddr": "1111JoeZHDYXqyAgo89VaidQnp7W7M9pvdkFUJTqEBU7SHKx6WF2z",
        "shortDesc": "Donald Duck for Board Member",
        "yesAddr": "1111rbdV9Lsw6DyMSq8ySXDacX7pRUxmVGoYho9gGtfZcQYFdAN42"
      },
      "Board: RR": {
        "noAddr": "1111swBFUPVRwR4ugkDBCvrLwPeR1621B1cHQf3cAkNxt3Zad2eac",
        "shortDesc": "Road Runner for Board Member",
        "yesAddr": "1111krbAKSbyGA9vfa7w4K2pKAxZZn6qjaVEduDLWotDZ8HLt2aXR"
      }
    }
```

**Comment by tgrospic** [comment]
@jimscarver thanks for reporting this error. It's a situation when only one value is returned and the code was expecting to be an array.

I fixed the bug and result is printed to the log. Inline display after the button is not meant to be for large output but only for primitive types so I think it's OK to just display generic string for objects _[object Object]_.

![image](https://user-images.githubusercontent.com/5306205/93030212-9907cb80-f621-11ea-9153-da98fc370d0f.png)

Commit with the fix on [rnode-client-js](https://github.com/tgrospic/rnode-client-js) repo.
https://github.com/tgrospic/rnode-client-js/commit/1312d92b84f014704c55a3e906a3724059a3d80a

**Comment by dckc** [comment]
I suggest transferring this issue to the https://github.com/tgrospic/rnode-client-js repo

**Comment by tgrospic** [comment]
@jimscarver can you confirm this is now working as expected?
