### ISSUE TITLE
why rchain encoding protobuf, scala codec in different layer

### ISSUE THREAD

**Issue by zsluedem** [rchain/rchain#3126]
Currently, rnode is using two kinds of encoding. 

1. protobuf
2. scala codec

In the blockstorage and network part, protobuf is in use while in the rspace code storage, we use scala codec for data storage. 

I don't know why rnode used scala codec for rspace storage since we already got https://github.com/rchain/rchain/blob/dev/models/src/main/protobuf/RhoTypes.proto proto definition for these data types.

Question:
Why rnode used scala codec encoding for rspace storage?

**Comment by tgrospic** [comment]
Yes, this is strange that tuple space is serialized with scodec. This includes types [Trie](https://github.com/rchain/rchain/blob/5f7f91e6257a46f056f55cfc97fb4cfb369f236c/rspace/src/main/scala/coop/rchain/rspace/history/History.scala#L45) for history store and [PersistedData](https://github.com/rchain/rchain/blob/8517e321c2884dff6c0ce5f72e6998876b98fcda/rspace/src/main/scala/coop/rchain/rspace/history/ColdStore.scala#L62) for cold store (+ Blake256Hash codec).
These types are not the same types as _RhoTypes.proto_ which are used to serialize Rholang terms, also exposed in Rholang through `toByteArray`.

**Comment by zsluedem** [comment]
There are some codec is not consistent because https://github.com/rchain/rchain/blob/d270bd669e5d73f37340cc2fc427e3e97264c21a/shared/src/main/scala/coop/rchain/shared/Serialize.scala#L23-L62 the method `toCodec` would add variableSizeBytesLong in front of the bytes. So if somewhere in the codes did something like below

```
val serialize: Serialize[A] = Serialize()
val codec = serialize.toCodec
val serialize2: Serialized[A] = Serialize.fromCodec(codec)

serialize != serialize2
```

these things happened in our codes which make https://github.com/rchain/rchain/blob/d270bd669e5d73f37340cc2fc427e3e97264c21a/rspace/src/main/scala/coop/rchain/rspace/RSpaceOps.scala#L29 and https://github.com/rchain/rchain/blob/d270bd669e5d73f37340cc2fc427e3e97264c21a/rspace/src/main/scala/coop/rchain/rspace/history/HistoryRepositoryImpl.scala#L39 are not the same

**Comment by zsluedem** [comment]
bors merge

**Comment by zsluedem** [comment]
> Currently, rnode is using two kinds of encoding.
> 
> 1. protobuf
> 2. scala codec
> 
> In the blockstorage and network part, protobuf is in use while in the rspace code storage, we use scala codec for data storage.
> 
> I don't know why rnode used scala codec for rspace storage since we already got https://github.com/rchain/rchain/blob/dev/models/src/main/protobuf/RhoTypes.proto proto definition for these data types.
> 
> Question:
> Why rnode used scala codec encoding for rspace storage?

The question is actually wrong. In the rspace storage , it is actually using a wrapper codec with protobuf serializer below.

https://github.com/rchain/rchain/blob/8f2924c2a4057b72a640c6e097025989090f559c/rholang/src/main/scala/coop/rchain/rholang/interpreter/storage/package.scala#L67-L77

**Comment by nzpr** [comment]
What is the current understanding? Can we use only protobuf and get rid of scodec?

**Comment by zsluedem** [comment]
Close it because it is more like a question and it is answered.
