### ISSUE TITLE
Block merge conflicts detectors

### ISSUE THREAD

**Issue by zsluedem** [rchain/rchain#3139]
## Overview
In order to merge two blocks, we need a detector to detect comm-event conflicts between the comm events in different blocks in different branches.

We got some related works before -> 
1. https://github.com/rchain/rchain/blob/c07671c4543bd16d2ae3258a1288425273e1a71b/casper/src/test/scala/coop/rchain/casper/batch1/MergeabilityRules.scala (original test for mergibilty rules)
2. https://github.com/rchain/rchain/blob/c07671c4543bd16d2ae3258a1288425273e1a71b/casper/src/test/scala/coop/rchain/casper/batch1/MultiParentCasperMergeSpec.scala (merge spec tests)
3. https://docs.google.com/spreadsheets/d/1pABqArF9e8HRTO9zSefp93mIVUm91avekeDgqSEw0R8/edit#gid=0 merge rules created by Mike
4. https://github.com/rchain/rchain/blob/c07671c4543bd16d2ae3258a1288425273e1a71b/casper/src/main/scala/coop/rchain/casper/TuplespaceEvent.scala (original event conflicts comparing)
5. **key conflicts function** for detect conflicts now https://github.com/rchain/rchain/blob/c07671c4543bd16d2ae3258a1288425273e1a71b/casper/src/main/scala/coop/rchain/casper/EstimatorHelper.scala#L50-L76

### Design
1. By @tgrospicthe design spec for block merging which mentions the way to resolve conflicts.  https://github.com/rchain/rchip-proposals/issues/23
2. @zsluedem mentioned in the dev standup `The conflicts detect action should happen when a node adds a block instead of when a node tries to merge two blocks`. @leithaus Said `Yes` it means the node should keep track on the conflict comm events between branches in the dag so that we need a persistent store for that

**Comment by zsluedem** [comment]
https://github.com/rchain/rchip-proposals/issues/23

**Comment by zsluedem** [comment]
In the current implementation, for `Join` operation, the node would consider any channel with joins that happened in two-planned-to-merge-blocks as conflicts. But with the current [test cases](https://github.com/rchain/rchain/blob/c07671c4543bd16d2ae3258a1288425273e1a71b/casper/src/test/scala/coop/rchain/casper/batch1/MergeabilityRules.scala#L436-L624) and [MergeableRules](https://docs.google.com/spreadsheets/d/1pABqArF9e8HRTO9zSefp93mIVUm91avekeDgqSEw0R8/edit#gid=0), I can not find anything relates to that.

**Comment by zsluedem** [comment]
In some join cases, conflict can not be detected from the event logs.

```
    *           MergedBlock
    *       /               \
    * B2 Rho("@1!(1)")     B3 Rho("@0!(0)")
    *       \              /
    *             B1    Rho("for (_ <- @0;_ <- @1) { 0 }")
    *
```

The joins on the `B1` would match on `MergedBlock`.

But the eventLogs on B2 and B3 are just linear produce on different channels which is mergeable.

**SOLUTION**:
For the case above is to read joins already in the tupleSpace in B1 and make sure the produce doesn't conflict.

**Comment by zsluedem** [comment]
Another join case, conflict can not be detected from just event logs.

```
   MergedBlock
   /                 \
B2  Rho("@1!(0)")      B3 Rho("for (_ <- @0;_ <- @1) { 0 }")
   \         /
      B1 Rho("@0!(0)")
```
The produce in B2 could match B3 if they merged. But from the events log, in this case we can not detect conflicts.

**Solution**:
Read the data from the join channel happened in B3 already in B1 and make sure join can not match with exist tupleSpace.

**Comment by zsluedem** [comment]
In one of the dev stand-ups, we discussed the situations below

```
   MergedBlock
   /                 \
B2  Rho("@1!(0)")      B3 Rho("for (_ <- @0;_ <- @1) { 0 }")
   \         /
      B1 Rho("for(_ <- 0) {1}")
```

and
 
```
   MergedBlock
   /                 \
B2  Rho("@1!(0)")      B3 Rho("for (_ <- @0;_ <- @1) { 0 }")
   \         /
      B1 Rho("Nil")
```

We have discussed that the two situations above are not very clear. It might depend on how **joins** really work which are not very clear now.**Join** could work like a greedy one which would consume any possible produces or a lazy one which would wait for all the produces to happen to consume.

**As @leithaus suggested, we should consider the unclear cases as conflict right now**

**Comment by zsluedem** [comment]
One more dilemma when detecting the conflicts.

```
   MergedBlock
   /                 \
B2  Rho("@0!(0)")      B3 Rho("for (_ <- @0) { 0 }")
   \         /
      B1 Rho("for(_ <- 0) {1}")
```

```
   MergedBlock
   /                 \
B2  Rho("@0!(0)")      B3 Rho("for (_ <- @0) { 0 }")
   \         /
      B1 Rho("Nil")
```

In the version of previous dev implemented https://github.com/rchain/rchain/blob/08711db307e8cadf23455b145b5073bbf384abe2/casper/src/main/scala/coop/rchain/casper/TuplespaceEvent.scala#L69-L90

The first one is mergeable while the second one is conflict. Actually there is no disagreement and confusion that the second case is a conflict case.

I think the first one is mergeable bacause B2 doesn't compete the data against B3 to generate a comm event which in my perspective is OK.

The devs had several conversations these days , actually I got different answers on different days. 
The first time I brought up this, the dev agrees that the first one is a mergeable case.
The second time I brought up with this, the dev turns out to be not that sure and think the first one is a conflict case.

If the first case is conflict, how will the case below be?
```
   MergedBlock
   /                             \
B2  Rho("@0!(0)|for(_ <- 0) {1}")      B3 Rho("for (_ <- @0) { 0 }")
   \                                    /
      B1 Rho("Nil")
```

**Comment by tgrospic** [comment]
> I think the first one is mergeable bacause B2 doesn't compete the data against B3 to generate a comm event which in my perspective is OK.

The first case is mergeable from left side, when B3 is merged to B1->B2 branch. Comm event on zero will already happen so when B3 merges it will just add new consume.
But looking from the right, B2 merged to B1->B3 branch. Two consumes will be in tuple space and produce from B2 will be in conflict. This will basically be the similar case to the second example.
In we detect conflict from any side the merging should be considered in conflict.

The third example should not happen. In B2 `Rho("@0!(0) | for(_ <- 0) {1}")` is reducible term and if executed it will not leave anything in tuple space. So after that B3 is not in conflict and can be merged.

**Comment by zsluedem** [comment]
```
 MergedBlock
 /                               \
B2 Rho("@0!(0)")      B3 Rho("Nil")
\                                 /
BaseState Rho("for(_ <- 0) {1}")
```
As discussed with @leithaus, the case above is **conflicting** because

1.BaseState + B3 = "for(_ <- 0) {1}|for(_ <- 0) {1}" = B4
2.BaseState + B2 = "Nil" = B5
(Baes + B3) + B2 != (Base + B2) + B3

Anyway, personally, I think the case above should be **mergeable**. If we take the case above a conflict case, it is not possible to develop a mergeable dapp and even worse case is that one person can easily keep deploying something like above to reject all the deploys in a block which is a very **serious attack vector**.

**Comment by tgrospic** [comment]
@zsluedem I agree with you that conflicts like this can be detected in many deploys but **equality** of merged states in both directions is even more **serious**.
So I want to be on your side and not to break merged equality, maybe the calculation is wrong?

First I want to distinguish between `B` as a state which this block produced and a trace `Tr` which contains changes which are applied to create the new block state (`B2 = B1 + Tr2`).
With this we cannot merge states or blocks directly `B3 = B1 + B2`. We can merge traces and apply to some starting state.
`B3 = B1 + (Tr1 /\ Tr2)` if `Tr1 /\ Tr2` is without conflicts.

```
        MergedBlock
   /                          \
B2 Rho("@0!(0)")             B3 Rho("Nil")
Tr2 [-for(_ <- 0) {1}, +1]   Tr3 []
   \                          /
    B1 Rho("for(_ <- 0) {1}")
```
So in the above example, block `B1` is the base state, `Tr2` and `Tr3` are the changes for block B2 and B3. `Tr2` change means remove _consume_ from the state and `Tr3` is empty.
If we now try to apply merge rules situation is clear that it's a mergable case.
```
B1 + Tr2 /\ Tr3 == (B1 + Tr3) + Tr2 == (B1 + Tr2) + Tr3
```
But if `Tr3` also mentioning consume on @0 it will conflict because of race on the same channel.
```
      MergedBlock
   /                          \
B2 Rho("@0!(0)")              B3 Rho("for(_ <- 0) {1}")
Tr2 [-for(_ <- 0) {1}, +1]    Tr3 [+for(_ <- 0) {1}, +1]
  \                           /
    B1 Rho("for(_ <- 0) {1}")
```
But what if in base state is a contract and B2 and B3 have only produces. Resulting trace for each block will only contain executed contract continuations, which if not in conflict, can be merged.
```
      MergedBlock
  /                   \
B2 Rho("@0!(0)")      B3 Rho("@0!(1)")
Tr2 [+1]              Tr3 [+1]
  \                   /
 B1 Rho("for(_ <= 0) {1}")
```
This means, even if contract is in the registry and multiple blocks have _sends_ on the same channel, it **can be merged**!

**Comment by zsluedem** [comment]
![image](https://user-images.githubusercontent.com/13496262/103055843-57020480-45d6-11eb-9bc2-be79df68ea17.png)
New share from @leithaus

**Comment by nzpr** [comment]
The latest implementation of conflict detector is in <https://github.com/rchain/rchain/pull/3312>
But this issue should has been closed long time ago - github does not do that for some reason
