### ISSUE TITLE
Upgrade Cats Effect library because of Deferred improvements

### ISSUE THREAD

**Issue by tgrospic** [rchain/rchain#3142]
## Overview
From Cats Effect version 2.2.0 release notes there should be _significant performance improvements_ for Deferred feature which we are extensively using in RChain project.

This is a good motivation for upgrade to new version on Cats Effects. Currently we are using version 2.0.0.
https://github.com/rchain/rchain/blob/44294ea/project/Dependencies.scala#L12

> The Deferred primitive is one of the most powerful and most-used utilities in the Cats Effect library outside of IO itself. It is, for example, the foundation of most of fs2's concurrency mechanisms. This release contains significant performance improvements within this abstraction, with a particular focus on lowering memory pressure. This should result in a very significant, user-visible jump in performance across most real-world applications.

https://github.com/typelevel/cats-effect/releases/tag/v2.2.0

@9rb I think you already have some insight what preventing us to use the new version. Could you please provide more info here.

**Comment by 9rb** [comment]
My initial experimentation with cats effect 2.2 required replacing MVar (deprecated) with MVar2. But there are probably additional things to take care of. Once my local environment is up, I'll identify and resolve those
