### ISSUE TITLE
New BlockMessage data structure

### ISSUE THREAD

**Issue by zsluedem** [rchain/rchain#3150]
## Overview

Below is how the current blockMessage structure looks like https://github.com/rchain/rchain/blob/cf6f2da2d1b8b30e953f60bff21cc5cde7cc49be/models/src/main/protobuf/CasperMessage.proto#L87-L99 .

Based on the [discussion](https://github.com/rchain/rchip-proposals/issues/23#issuecomment-697369252), currently the blockMessage data structure doesn't get the ability to describe whether the deploy is rejected in merging blocks. RChain should introduce some addtional messages in the block for that.

Besides that, there were discussions between the devs (@tgrospic , @nzpr and @zsluedem)  about the bonding info in the blockMessage doesn't contain `isActive` message which is very important. 

**The changes of the blockMessage should go into [RChips](https://github.com/rchain/rchip-proposals), too.**

### Impact

The blockMessage should be changed and the explorer or any infrastructures relate to blockMessage should be impacted.

This kind of update should be a **hard-fork**.

### Design

1. introduce  `reject deploy` field in the blockMessage
2. introduce `isActive` field in bondInfo in the blockMessage 
3. split eventLogs into precharge, refund and user
4. MergerStateHash?(need discussion)

**Comment by zsluedem** [comment]
BlockMessage also includes **ProcessedDeploy** data structure.

https://github.com/rchain/rchain/blob/cf6f2da2d1b8b30e953f60bff21cc5cde7cc49be/models/src/main/protobuf/CasperMessage.proto#L145-L151

Based on https://github.com/rchain/rchain/issues/3147, RChain might need to introduce `UserDeployError` in the `ProcessedDeployProto`

**Comment by zsluedem** [comment]
As for EventLog, the node is mixing `PrechargeSystemDeploy` and `RefundSystemDeploy`eventlogs  with `UserDeploy` eventlogs together in the `ProcessedDeploy`.->https://github.com/rchain/rchain/blob/dev/models/src/main/protobuf/CasperMessage.proto#L148

Maybe it makes more sense to serparate these three kinds of eventLogs which can help developer understand their own event logs.

**Comment by tgrospic** [comment]
I agree, it makes sense to have separate log for user and system deploy for easier use.

**Comment by zsluedem** [comment]
Do we need mergedStateHash?

**Comment by tgrospic** [comment]
Closing this issue because block is extended with rejection field.

There is new related new issue to change rejection field to be a flag #3372.
