### ISSUE TITLE
set stored on chain at uri cannot be retrieved./ Error: Multiple expressions given.

### ISSUE THREAD

**Issue by jimscarver** [rchain/rchain#3151]
### What did you expect to see?
`(Set("1111tBR2JPWkpRmXXqsRU4aCK3rMcoBFgjEQpTJKED6VxYt7WuLi7","1111mEviz9tTWe8WAFSPhySkSwisQHSJyzVJEhoRCbMtMJ9qJonu","111125kxus7ZfRnR9a1bJHoVhqreBmwfw3vN8M1pnG9BfeXm3gTRcn","xx")`
### What did you see instead?
nothing or doing any operation on it deploy error or `Error: Multiple expressions given.`
### Steps to reproduce the bug

```
new return(`rho:rchain:deployId`),
  insertArbitrary(`rho:registry:insertArbitrary`)
in {
  new uriCh, valueCh in {
    insertArbitrary!(Set("1111tBR2JPWkpRmXXqsRU4aCK3rMcoBFgjEQpTJKED6VxYt7WuLi7","1111mEviz9tTWe8WAFSPhySkSwisQHSJyzVJEhoRCbMtMJ9qJonu","111125kxus7ZfRnR9a1bJHoVhqreBmwfw3vN8M1pnG9BfeXm3gTRcn"), *uriCh) |
    for (@uri <- uriCh) {
      return!(("URI", uri))
    }
  }
}
`(URI, rho:id:ds6o6ebk5api6n6g87jz9ff8i4arjbmo3mpc47p43e3wazbp14qqro) // cost: 86027`
```
```
new return(`rho:rchain:deployId`),
  lookup(`rho:registry:lookup`)
in {
  new valueCh in {
    // Fill in registry URI: `rho:id:11fhnau8j3...h4459w9bpus6oi`
    lookup!( `rho:id:ds6o6ebk5api6n6g87jz9ff8i4arjbmo3mpc47p43e3wazbp14qqro` , *valueCh) |
    for (@value <- valueCh) {
      return!((value.union("xx")))
    }
  }
}
```
`Deploy error when executing Rholang code.`
on explor deploy I get
`Error: Multiple expressions given.`
### What version of RNode are you using?
RChain Node 0.9.25.4 (41a42a330143e2451097cefa36b9b733b989b4f4)
### What is your environment?

https://tgrospic.github.io/rnode-client-js/ on testnet node0

**Comment by nzpr** [comment]
I suspect this piece of code 
<https://github.com/rchain/rchain/blob/09d9acc916e008dc93a7289202262fd5a4d9d41d/rholang/src/main/scala/coop/rchain/rholang/interpreter/Reduce.scala#L1123-L1142>, looks like it is used when you get value from map (so registry)
which uses `evalSingleExpr` throwing this error.

**Comment by tgrospic** [comment]
@jimscarver the problem here is not in the registry but in the use of `Set.union` method. It's accepting another `Set` instance and not the element itself.
To get correct return value it should be something like `return!((value.union(Set("xx"))))`.

**Comment by jimscarver** [comment]
Thanks. I thought I tested contains() also but it is working now. Sorry for the confusion.
