### ISSUE TITLE
Enable autopropose

### ISSUE THREAD

**Issue by nzpr** [rchain/rchain#3247]
## Overview
Now the only way to issue a block is a node operator to call internal API port.
This is not user friendly, sustainable, also validator will be subject to ejecting if it does not propose in correct way.
How node proposes block should defined by shard behaviour.

NOTE: triggering propose does not mean issuing a block. If synchrony constraint fails, node won't create block.

### Design
Proposer should maintain the following features:
1. only one propose should be happening at a time
2. return to caller propose ID, or None if another propose is in progress
3. should have an Mvar variable denoting that propose has been triggered, but Proposer as not able to process it because another propose is in progress. In that case propose should be triggered after one that is in progress finishes.
4. should maintain Deferred propose result inside node state, so checking proposer status is cheap.

There are several places where propose can be called:
1. internal API port
2. after block added
3. after deploy received

### Steps to implement the solution
1. implement proposer (done)
2. enable propose triggering wen `--autopropose` run option is provided

**Comment by tgrospic** [comment]
It would be nice if proposer can return some info when another propose is in progress, like number of deploys, future block info, ETA, etc.

Is it make sense for auto propose can be triggered from API without restarting the node?

**Comment by nzpr** [comment]
> It would be nice if proposer can return some info when another propose is in progress, like number of deploys, future block info, ETA, etc.

Agree, for now seqNum can be returned

> Is it make sense for auto propose can be triggered from API without restarting the node?

not sure, its a complication, nice to have feature imo, but not required for now

**Comment by nzpr** [comment]
Weird that github does not autoclose this
