### ISSUE TITLE
Cache fault tolerance in block metdata

### ISSUE THREAD

**Issue by nzpr** [rchain/rchain#3252]
## Overview
Looking for fault tolerance for old blocks is resource consuming. There should be a way to avoid unnecessary computation.

### Impact
<https://github.com/rchain/rchain/pull/3251> and <https://github.com/rchain/rchain/pull/2947> should be reverted

### Design
it is reasonable to accumulate and cache fault tolerance in block metadata

**Comment by tgrospic** [comment]
Obsolete, fault tolerance is not used with multi-parent finalization.
