### ISSUE TITLE
Should Joins be lazy or greedy?

### ISSUE THREAD

**Issue by zsluedem** [rchain/rchain#3256]
THis is a question extended by discussion in https://github.com/rchain/rchain/issues/3139#issuecomment-734655564.

# Should Joins be lazy or greedy?

This is acutually not something which haven't decided in current implementation(version https://github.com/rchain/rchain/tree/2b19649ed29b730dcf814c29faa2f608a9d1858c). In the current implementation, **Joins are lazy**.

## Lazy Joins
```
Rho("for (_ <- @0;_ <- @1) { 0 }")
    |
    v
Rho("@0!(0)")    **No COMM event**
    |
    v
Rho("for (_ <- @0) { 0 }")  **One COMM event**
```
The above example shows how **lazy** joins work. **Lazy Joins** require **all** the channels got some matched data to trigger COMM events. And this is how the current version is working right now.

## Greedy Joins
```
Rho("for (_ <- @0;_ <- @1) { 0 }")
    |
    v
Rho("@0!(0)")    **One COMM event**
    |
    v
Rho("for (_ <- @0) { 0 }")  **No COMM event**
```
The above example shows how **greedy** joins work. **Greedy Joins** only require **one** of the join channels got matched data to trigger one COMM event. (This is my assumption, though. @leithaus needs to confirm)

## My point of view
**I think** `Joins` were not originally introduced in Rholang at the very first time and **I think** they were introduced to avoid callback hell which if you need to wait for the data from two different channels you have to write something like below
```
for (_ <- @0) { 
  for (_ <- @1 ) 
    { P }
}
```
the example can cause callback hell very easily which most developers want to avoid.

If `Joins` are introduced just to avoiding callback hell, then it should be a greedy case which is more like a syntactic candy.

However, if `Joins` are introduced to be lazy, that would be more like introducing a **totally new feature** which channels can wait for each other. I am not actually sure if that causes some problems for Rho calculus. But apparently, lazy ones would definitely introduce a lot more different cases in a practical world(like conflict detection).

It would be better to learn more from @leithaus

**Comment by nzpr** [comment]
IMO joins have to be lazy, as to execute continuation you need data from all channels.

**Comment by zsluedem** [comment]
Lazy join can lead to dead lock https://github.com/rchain/rchain/blob/dev/docs/rholang/rholangtut.md#dining-philosophers-and-deadlock
Thanks for @tgrospic information

**Comment by zsluedem** [comment]
After some thinking, I don't think Join is the only way to solve deadlock. This problem can be addressed by the rholang developer like any other languages. And I think for some more complicated program, Join can not be useful for situation but embeded for can do.

**Comment by zsluedem** [comment]
Thanks to @JosDenmark pr https://github.com/rchain/rchain/pull/3279.
https://github.com/rchain/rchain/blob/0b2cb9a43347af970a6a4e0c04be9fa17226e371/rholang/src/test/scala/coop/rchain/rholang/interpreter/SequentialConsumeSpec.scala
SequentialConsume would be introduced. After that, the developers can choose from lazy ones and greedy ones.
