### ISSUE TITLE
Read-only node should not accept deploys

### ISSUE THREAD

**Issue by tgrospic** [rchain/rchain#3266]
### What did you expect to see?
Deploy to read-only should return an error.

### What did you see instead?
Read-only node accepted deploy as it was the validator.

### Steps to reproduce the bug
Deploy to test net read-only node.
```
curl https://observer.testnet.rchain.coop/api/deploy \
  --data-binary '{"data":{"term":"Nil","timestamp":1607687297250,"phloPrice":1,"phloLimit":250000,"validAfterBlockNumber":18},"sigAlgorithm":"secp256k1","signature":"3045022100b8a9a6176fd9b8f394bafcad987524996d25102eaa83560e1da578ff444d40db022047e66f7d074740d51df429e84a16cfb9a4223eee225fa83c053c03ed70207d12","deployer":"04eb79a155592889626968233a30d3cae7c1d9ce664017ccc5ebf627b053d28f44158ad47b2c47bad4a49d88c568951a9dd7597b2aa612a2374070400c5499e22c"}'
```
Returned result is successful.
```
"Success!\nDeployId is: 3045022100b8a9a6176fd9b8f394bafcad987524996d25102eaa83560e1da578ff444d40db022047e66f7d074740d51df429e84a16cfb9a4223eee225fa83c053c03ed70207d12"
```

:heavy_plus_sign: It would be nice for checking if node is a validator is more precise than just checking if private key is provided in the configuration.

## Solution

If private key is supplied when running a node it's more complicated to check if this private key is bonded and node can produce blocks, so this task should be done in two steps.

- [x] When private key is NOT supplied and node operates as read-only node. Throw an error when deploy is received.
- [ ] When private key is supplied, check if private key is bonded and node is a validator which can create blocks and accept deploys. Throw an error if not bonded when deploy is received.
  - There is also edge case when a new validator _waiting_ for the next epoch where it will be bonded and start producing blocks. In that case it would be useful that in some amount of block before epoch change it can accept deploys.
  - This situation can also happen when validator is slashed and still have private key but cannot produce new blocks.

Another option would be for read-only node to _relay_ deploys to a validator node. In that case deployer must have a way to check deploy results and status. FYI @zsluedem

**Comment by zsluedem** [comment]
It would be better that the read-only node  can forward the deploy to validator. In that case the exchange only need observer.

**Comment by stanislavlyalin** [comment]
> When private key is NOT supplied and node operates as read-only node. Throw an error when deploy is received.

This first part made in [PR #3578](https://github.com/rchain/rchain/pull/3578)
