### ISSUE TITLE
One public key can only insert one name in the public registry

### ISSUE THREAD

**Issue by zsluedem** [rchain/rchain#3296]
Why does one key can only insert only once in the registry.

Following the example here https://github.com/tgrospic/rnode-client-js/blob/master/src/nodejs/client-insert-signed.js

One public key can only insert one in the public registry.
The second insert with the same public key would return `Nil`.

Probably because the codes below.

https://github.com/rchain/rchain/blob/dev/casper/src/main/resources/Registry.rho#L397-L431

**Comment by tgrospic** [comment]
Maybe it's better to say that Registry uri corresponds or it's derived from public key. Similar how REV address has corresponding public/private key.

Will as you pointed out _buildUri_ generates address, always the same from the same key.
https://github.com/rchain/rchain/blob/7726d2c1977f93f290aeb627b6148b5556458053/rholang/src/main/scala/coop/rchain/rholang/interpreter/registry/Registry.scala#L8-L15

Insert signed to the Registry can be performed multiple times which has meaning of updating the value and deleting the previous one.

@JoshOrndorff pointed out that in both cases (signed and arbitrary insert) uri is the same which makes it very difficult to check if registered value can be mutated or not, just by checking the address format which I think is very useful.
https://rchain.atlassian.net/browse/RCHAIN-2371
