### ISSUE TITLE
Fix failing test in block-merge branch

### ISSUE THREAD

**Issue by zsluedem** [rchain/rchain#3310]
After https://github.com/rchain/rchain/pull/3201, some tests are failing but the dev decide to fix those failing tests later. Create this issue the mark those failing tests and make sure this must be addressed later.

1. after #3201, ci test failing  https://github.com/rchain/rchain/runs/1633835972?check_suite_focus=true. Those tests are ignored in https://github.com/rchain/rchain/pull/3309

**Comment by nzpr** [comment]
@zsluedem is this the same as https://github.com/rchain/rchain/issues/3277?

**Comment by zsluedem** [comment]
> @zsluedem is this the same as #3277?

@nzpr Oh. Your title is special . I didn't notice. close it and move to #3277
