### ISSUE TITLE
Hard Fork 2 - candidate fixes

### ISSUE THREAD

**Issue by zsluedem** [rchain/rchain#3315]
## Overview

This is an issue for the fixes related to **Hard Fork 2**. It should show all the troubles exist in the current codebase but these troubles are very difficult to fix for the current existing running network.

Coop introduces a really really hard fork --> a new genesis with a new state. 

And below are all the troubles that exist in current code base.

### Required
1. POS negative reward bugs. related issue https://github.com/rchain/rchain/issues/2956
1. POS internal state dump. related issue https://github.com/rchain-test/rchain-secure/issues/6
1. :heavy_check_mark: POS epoch length and quarantine length change (nothing to fix actually.Just startup parameter)
1. :heavy_check_mark: remove channel store(together with 7)@ #3394 #3474
1. :heavy_check_mark: trie object(emptyTrie, PointerBlock and etc.) encoding and hashing algorithm
https://github.com/rchain/rchain/pull/3497
1. :heavy_check_mark: change blockMessage protobuf(split event logs, etc.), related issue https://github.com/rchain/rchain/issues/3150
1. :heavy_check_mark: encoding and hashing algorithm for key and value object(channel, datum, continuation and joins) in trie.
https://github.com/rchain/rchain/issues/3384

### Optional
1. :heavy_check_mark: (ready) introduce rholang1.1, https://github.com/rchain/rchain/pull/3279
1. retain key in rholang treeHashMap #3329
1. implement traverse method in rholang treeHashMap
https://github.com/rchain/rchain/issues/3432
1. ~cold store exclude randomState~ outside of scope for HF2

### Impact

All the states in the existing mainnet would be lost.

**Comment by nzpr** [comment]
Do we have issues on #7?
Recent investigations shows that this channel encoding costs us quite a lot. When replaying multiple blocks in parallel this slows down processing - as you can see 25 sec for just opulating channels map.
<img width="1790" alt="Screenshot 2021-02-11 at 10 14 50" src="https://user-images.githubusercontent.com/1746367/107610138-fc8a3980-6c51-11eb-8f06-244f470c3137.png">
http://jaeger.dev.rchain.coop/trace/ea5982c71c76206e (link might be broken after some time).

And even when replaying self proposed block in isolation - its quite intensive operation, 25% of the time spent there.
<img width="1790" alt="Screenshot 2021-02-11 at 10 16 00" src="https://user-images.githubusercontent.com/1746367/107610207-26436080-6c52-11eb-878c-aa5ff898253a.png">

Also, how its done now - in Checkpoint, this calculation happens twice - both on play and replay

**Comment by jimscarver** [comment]
[recover rev locked in contract addresses](https://docs.google.com/spreadsheets/d/17Vl0BzJZRuh5FflnEA64Cy7dvewh2qVXAYqr6uZ-XeQ/edit#gid=945391069&fvid=1940700462)

**Comment by tgrospic** [comment]
Closing because the purpose of this epic issue is fulfilled. Optionally, Rholang 1.1 is already merged to dev branch and will be part of v0.13.0 release.
