### ISSUE TITLE
Optimize block metadata store intialization

### ISSUE THREAD

**Issue by tgrospic** [rchain/rchain#3323]
## Overview
Currently when node starts, block metadata store is read to create in-memory representation (parent, child relation, ...).

This process is to slow and must be optimized. The solution is to improve iteration of LMDB records.

**Comment by zsluedem** [comment]
> The solution is to improve iteration of LMDB records.

I am curious on how to do that. 

Just want to point out that building finalized block sets consume a lot of memory which it should not be. This should be optimized also. Maybe I should start another issue.

**Comment by tgrospic** [comment]
> Just want to point out that building finalized block sets consume a lot of memory which it should not be. This should be optimized also. Maybe I should start another issue.

This is part of the same problem. Currently `toMap`  on KV Store does not offer to make a projection of values stored and because of that the whole value is loaded into memory. I'll create version which can select only part of the value and reduce amount of data loaded into memory.
