### ISSUE TITLE
Fix  rchain/node/src/main/scala/coop/rchain/node/Main.scala 

### ISSUE THREAD

**Issue by 9rb** [rchain/rchain#3325]
## Overview
 rchain/node/src/main/scala/coop/rchain/node/Main.scala   has comments that say 
 
 private def startNode[F[_]: Monixable: ConcurrentEffect: Parallel: ContextShift: Timer: ConsoleIO: Log: EventLog](
      options: commandline.Options
  )(implicit s: Scheduler): F[Unit] = Sync[F].defer {
    // Create merged configuration from CLI options and config file
    val (nodeConf, profile, configFile, kamonConf) = Configuration.build(options)
    // This system variable is used in Logger config file `node/src/main/resources/logback.xml`
    val _ = System.setProperty("rnode.data.dir", nodeConf.storage.dataDir.toString)

    // and start node
    // TODO : Enable it earlier once we have JDK with https://bugs.openjdk.java.net/browse/JDK-8218960 fixed
    // https://www.slf4j.org/legacy.html#jul-to-slf4j
    SLF4JBridgeHandler.removeHandlersForRootLogger()
    SLF4JBridgeHandler.install()

This JDK bug is now fixed https://bugs.openjdk.java.net/browse/JDK-8218960

So we should take the necessary remedial action

**Comment by tgrospic** [comment]
This is duplicated issue, @9rb you added it as part of #3001 (Review the TODO comment in Main.scala if it's still relevant because referenced JVM bug seems resolved.).

**Comment by 9rb** [comment]
Closing because it is listed in  #3001 as tgrospic mentioned above
