### ISSUE TITLE
Refactor KeyValueCache (implement size limit)

### ISSUE THREAD

**Issue by tgrospic** [rchain/rchain#3340]
## Overview

NOTE: Issue is extended to also implement size limit so that memory doesn't grow indefinitely. 

Change `KeyValueCache#get` method to return `F[Option[V]]` because *fallback* may not always be available in which case the question is what to supply as `F[V]`. When Option is returned it's easy to do _orElse_ with fallback parameter.
https://github.com/rchain/rchain/blob/230b2515f369af344e83af30fb31af83dce44bc8/shared/src/main/scala/coop/rchain/store/LazyAdHocKeyValueCache.scala#L8-L9

Here is an example how `HashHistoryReader` can be refactored using `OptionT`.
```scala
override def getRichDatums(hash: Blake2b256Hash): F[Seq[RichDatum[A]]] = {
  def cachedData: F[Option[Seq[RichDatum[A]]]] = ??? // Returned from cache

  val data = OptionT(fetchData(hash))
    .semiflatMap {
      case DataLeaf(bytes) =>
        decodeDataWithIntermediaries[A](bytes).map(Function.tupled(RichDatum.apply)).pure[F]
      case p =>
        new RuntimeException(
          s"Found unexpected leaf while looking for data at key $hash, data: $p"
        ).raiseError[F, Seq[RichDatum[A]]]
    }
    .getOrElse(Seq.empty[RichDatum[A]])

  OptionT(cachedData) getOrElseF data
}
```

P.S.
`OptionT` is similar in spirit to *fs2.Stream*, it doesn't contain many values but only one. It's also a small DSL for `F[_]` which has **introduction** functions (lift `F` values) and **elimination** functions (exit back to `F`).
Here are some similarities to fs2.Stream.
```scala
// Introduction - from F[_]
OptionT.liftF(F[A]) ~ Stream.eval(F[A])
OptionT(F[Option[A]]) ~ Stream.emits(Seq[A])

// Elimination - to F[_]
optT.value            ~ stream.compile.last
optT.getOrElseF(F[A]) ~ stream.compile.compile.lastOrError // sort of

// Map, tap with F[_]
optT.semiflatMap(A => F[B]) ~ stream.evalMap(A => F[B])
optT.semiflatTap(A => F[B]) ~ stream.evalTap(A => F[B])
```

**Comment by nzpr** [comment]
I guess `KeyValueCache ` is a bad name for what I tried to express. It's more a reader that caches data requested. In your code snippet `cachedData ` when called, will read from store in case there is no cache.

Its more like 
```scala
  override def getRichDatums(hash: Blake2b256Hash): F[Seq[RichDatum[A]]] = {
    val load = fetchData(hash).flatMap {
      case Some(DataLeaf(bytes)) =>
        Sync[F].delay(
          decodeDataRich[A](bytes).map(v => RichDatum(v.item, v.byteVector))
        )
      case Some(p) =>
        Sync[F].raiseError[Seq[RichDatum[A]]](
          new RuntimeException(
            s"Found unexpected leaf while looking for data at key $hash, data: $p"
          )
        )
      case None => Seq.empty[RichDatum[A]].pure
    }

    rSpaceCache
      .map(
        _.dtsCache.get(
          HistoryPointer(targetHistory.root, hash),
          load
        )
      )
      .getOrElse(load)
  }
```

**Comment by nzpr** [comment]
Measure of merging performance with and without caching

```grep "compute changes" /root/.rnode/rnode.log | sed "s/.*consumes \[//g" | sed "s/ ms]//g" |  awk -F : '{sum+=$0} END {print "AVG ",sum/NR}'```
AVG 118.056 ms => 214.645 ms

```grep "process trieAction" /root/.rnode/rnode.log | sed "s/.*trieActions \[//g" | sed "s/ sec]//g" |  awk -F : '{sum+=$0} END {print "AVG ",sum/NR}'```
AVG 5.06381s sec => 4.79681 sec

```grep "Merging done" /root/.rnode/rnode.log | sed "s/.*Merging done\. \[//g" | sed "s/ sec\]//g" |  awk -F : '{sum+=$0} END {print "AVG ",sum/NR}'```
AVG 7.22494 sec => AVG= 7.14132 sec

```grep "Indexing done" /root/.rnode/rnode.log | sed "s/.*Indexing done\. \[//g" | sed "s/ sec\]//g" |  awk -F : '{sum+=$0} END {print "AVG ",sum/NR}'```
AVG 36.8254 ms => AVG= 23.9202 ms

As expected, cache slightly helps to computing changes. But i does not worth pursuing right now and its easier just wipe out caching from codebase, as we have plans for making better code for cache.

So I'm closing this issue, cache support is removed for now in <https://github.com/rchain/rchain/pull/3359>.

**Comment by tgrospic** [comment]
Yes, you are absolutely right, my example is misleading because it's more about how to use the cache and not how to build it.

Here is better example. This is how should look like using of `fetchDataCached` function. This function should be _transformed_ version of `fetchData` function.

```scala
override def getRichDatums(hash: Blake2b256Hash): F[Seq[RichDatum[A]]] = {
  //    def fetchData(hash: Blake2b256Hash): F[Option[Seq[RichDatum[A]]]] = ???
  def fetchDataCached(hash: Blake2b256Hash): F[Option[Seq[RichDatum[A]]]] = ??? // fetchData with cache

  OptionT(fetchDataCached(hash))
    .semiflatMap {
      case DataLeaf(bytes) =>
        decodeDataWithIntermediaries[A](bytes).map(Function.tupled(RichDatum.apply)).pure[F]
      case p =>
        new RuntimeException(
          s"Found unexpected leaf while looking for data at key $hash, data: $p"
        ).raiseError[F, Seq[RichDatum[A]]]
    }
    .getOrElse(Seq.empty[RichDatum[A]])
}
```

So now the question is how to create a *cache manager* for any function `f : A -> Option[B]`?
