### ISSUE TITLE
Modify the DAG representation to support block merge

### ISSUE THREAD

**Issue by tgrospic** [rchain/rchain#3350]
## Overview
Currently view on the DAG can only be created using the most recent state of BlockDagStore. To be able to validate merged blocks created by other validators (with relaxed synchrony constraint) we need to be able to construct DAG view from perspective of that block, i.e. view on the DAG of peer validator at the beginning of block creation. When allowing proposing without requirement to wait for all other peer validators to issue new block, this might lead to difference between view on the DAG by block creator and of block validator.

### Design
Adjust `representation` method of BlockDagStorage to be able to ignore messages (and adjust corresponding indices) that are not in scope of a particular block.

**Comment by nzpr** [comment]
New version of finalizer https://github.com/rchain/rchain/pull/3388 makes sure that finalized block is defined only by latest messages. So merging scope is defined by latest messages. This covers part of the issue. 
Remaining part is to not have last finalized blocks persisted and treated as a mutable value but to compute it each time casper shapshot is created (for validation or block creation purpose), or maintain some map Set[LatestMessage] -> Last Finalized Block. Having caching it should not be computationally intensive.

**Comment by tgrospic** [comment]
> Remaining part is to not have last finalized blocks persisted and treated as a mutable value but to compute it each time casper shapshot is created (for validation or block creation purpose), or maintain some map Set[LatestMessage] -> Last Finalized Block. Having caching it should not be computationally intensive.

We can extend BlockMetaData with finalized flag and have this info for every block. Also I think we need info if block is directly or indirectly finalized for easier view on merging scopes and rejected deploys.
