### ISSUE TITLE
Boolean operators and/or are evaluated eagerly (add lazy &&/||)

### ISSUE THREAD

**Issue by tgrospic** [rchain/rchain#3362]
### What did you expect to see?
Boolean operators should lazy evaluate operands.

**UPDATE: Instead if changing behavior of existing `and` and `or` boolean operators, lazy variants will be added `&&` and `||`.**

### What did you see instead?
The error _Error: Method `get` is not defined on String._ is reported instead.

### Steps to reproduce the bug
`if(false and ("x".get(0))) {}` should not throw error because the first operand `false` makes the whole expression false.

https://github.com/rchain/rchain/blob/09d9acc916e008dc93a7289202262fd5a4d9d41d/rholang/src/main/scala/coop/rchain/rholang/interpreter/Reduce.scala#L605-L617

Related issue: #3344

**Comment by Isaac-DeFrain** [comment]
If we short-circuit the boolean evaluation semantics, do we only want the first conjunct to be considered? Is it useful to guarantee that if either conjunct has already evaluated to `false` then the entire conjunction evaluates to `false`. For example, should we have the same short-circuited behavior for `if(("x".get(0)) and false) {}`?

**Comment by tgrospic** [comment]
@Isaac-DeFrain I'd expect that conjunction terms are evaluated sequentially and short-circuit to happen after the first which makes the entire conjunction final. Do you have example of a language where this is different?

What immediately comes to mind is a more complex example. I think it would be difficult from a user perspective to always be sure what will be evaluated or what is already evaluated.
```scala
match 1 == 0 {
  x => if(("x".get(0)) and x) {}
}
```

**Comment by Isaac-DeFrain** [comment]
That's a fair point. While I'm not aware of any languages with the short-circuit evaluation I asked about, Rholang is not like any other language I've used so it doesn't seem entirely unreasonable for it to have a different evaluation strategy.

**Comment by zsluedem** [comment]
We should use new syntax to support short-circuit evaluator like other languages.

https://en.wikipedia.org/wiki/Short-circuit_evaluation

**Both eager evaluation and short-circuit are needed.**
