### ISSUE TITLE
Make encoding algorithm for channel hash consistent  

### ISSUE THREAD

**Issue by zsluedem** [rchain/rchain#3384]
## Current shortage of encoding

Despite of the protobuf encoding method we used for the `Channel Type` which is [Par](https://github.com/rchain/rchain/blob/13be1a71b8f59016179af832a0a00d7a0a96b282/models/src/main/protobuf/RhoTypes.proto#L31-L42), there are differences between the encoding of the [EventLog Channel Hash](https://github.com/rchain/rchain/blob/13be1a71b8f59016179af832a0a00d7a0a96b282/rspace/src/main/scala/coop/rchain/rspace/StableHashProvider.scala) and the encoding of the [HistoryReposity Channel Hash Key](https://github.com/rchain/rchain/blob/13be1a71b8f59016179af832a0a00d7a0a96b282/rspace/src/main/scala/coop/rchain/rspace/history/HistoryRepositoryImpl.scala#L63-L75) .

```

				  encodingAlg A	                               hashingAlgX
				  ---------------------> encodedType A---------------------------------->  channelHashA (used in BlockMessage)
				 /	                                                                                                                                   |
                                /                                                                                                                                         X
ChannelDataType                                                                                                                                      X can not convert channelHashA to channelHashB
				\                                                                                                                                         X
				 \  encodingAlg B                                       hashingAlgX with suffix                  v
				  ---------------------> encodedType B ---------------------------------->channelHashB (used in HistoryReposity)
```

Because of the differences above, we need to introduce [ChannelMap]() in block merging for accessing the data in HistoryRepo through `ChannelHash` in `BlockMessage`.

### The goal of the changes 

We need to change the encoding pattern to be like below.

```

                                     encodingAlgA                                            hashingAlgX                                                           
ChannelDataType -----------------------> encodedTypeA --------------------> channelHashA(used in BlockMessage) 
```
THEN
```

                                DatumHashAlg
                              ----------------------->   DatumChannelHashA(used in HistoryRepo)
                            /
                           /   ContinuationHashAlg
channelHashA ------------------------->  ContinuationChannelHashA(used in HistoryRepo)
                             \
                                \   JoinHashAlg
                                    -------------------->  JoinChannelHashA(used in HistoryRepo)
```

@tgrospic and @zsluedem  discussed this before and @tgrospic suggested putting some prefix bits in front of the `channelHashA` then we don't have to hash it again.  But it seems that this adding-prefix-bit way can to applied to `Joins` easily. 

After the changes are done, the channelMap should be removed.

### Impact

Need hard fork

### Dependencies

Nope

### Design

Need some discussions

**Comment by zsluedem** [comment]
![image](https://user-images.githubusercontent.com/13496262/116365312-b8153f80-a837-11eb-865e-7e62b7fa938a.png)
Prefix design based on @tgrospic

**Comment by tgrospic** [comment]
Reopening because another PR is linked to this issue.

**Comment by tgrospic** [comment]
As part of removing channels map (#3394, #3474), hashing of channels is unified for event log and storage.
