### ISSUE TITLE
Investigate user deploy error (REV transfer)

### ISSUE THREAD

**Issue by tgrospic** [rchain/rchain#3406]
### What did you expect to see?

User submitted deploy should execute successfully. I tried to repeat the same code locally (with different source REV address) and it executed without errors.

### What did you see instead?

Deploy is executed with error status. We need to investigate what is the reported error.
- https://revdefine.io/#/blocks/4fd206b6cf85852b1516da86bc683323514ebb2f1e9ecb73e784af807ae88d33/deploy/5a52aa5ec708f68cff36425aeef9876c592bae3347d5f32585d2ca3884826f13667a29e86d43bd65bf7f3a50399d13c646ce8425f7eb9173fe64d7545898b4061b
- https://observer.services.mainnet.rchain.coop/api/block/4fd206b6cf85852b1516da86bc683323514ebb2f1e9ecb73e784af807ae88d33

PR #3405 is created that adds additional logging for debugging.

The real solution must enable users to get the complete error when deploy execution failed. More info is in  issue #3147.

### What version of RNode are you using?

RNode version v0.10.2.

### What is your environment?

Deploy is submitted to RChain main net network.

**Comment by zsluedem** [comment]
I just ran #3405 with reporting and replay the block got the error below

```
11:06:13.535 [INFO ] [node-runner-53      ] [c.r.c.ReportingCasper$$anon$2] - trace block Some(Block #773500(4fd206b6cf...)-- Sender ID 04190524e1... -- M Parent Hash 14b8ccf326... -- Contents 8f03bcfd39...-- Shard ID root)                                                                                                                                   
11:06:13.545 [INFO ] [node-runner-53      ] [c.r.c.ReportingCasper$$anon$2] - No 4fd206b6cf85852b1516da86bc683323514ebb2f1e9ecb73e784af807ae88d33 reporting data in cached, going to replay                                                                                                                                                                         
("Finished transfer of ", 500000000, "REV to", "1111qAKSRoyCoKweFWeAXHDzzMXSL2om9Ly7YiqGhHFbFM2FvRx5K", "result was:", (true, Nil))
11:06:16.705 [INFO ] [node-runner-31      ] [c.r.c.u.r.InterpreterUtil$   ] - Deploy (5a52aa5ec708f68cff36...73fe64d7545898b4061b) errors: coop.rchain.rholang.interpreter.errors$OutOfPhlogistonsError$: Computation ran out of phlogistons.
11:06:22.314 [INFO ] [node-runner-41      ] [c.r.c.ReportingCasper$$anon$2] - Cache 4fd206b6cf85852b1516da86bc683323514ebb2f1e9ecb73e784af807ae88d33reporting data into mem. 
```

**Comment by jimscarver** [comment]
aedel had the same problem today deployid 2302c47b7780ad4b326e6224a1d08924f1c341a11c7f4d11185bec7a1950c8e86a03c922881c4aa91bf7985a89db9be0739aa3963c5392b154754b55766161421b

**Comment by tgrospic** [comment]
@jimscarver I tested transfer with the same target REV address and the cost was indeed over 250k (254845).

I merged your change (https://github.com/tgrospic/rnode-client-js/pull/28) to increase phlo limit and also set it as default for custom deploy. Thanks!

**Comment by tgrospic** [comment]
Closing issue as the resolution was to increase phlo limit. Transfer cost exceeded 250,000 phlogistons.
