### ISSUE TITLE
Rholang TreeHashMap would miss suffix value if "update" function stuck

### ISSUE THREAD

**Issue by zsluedem** [rchain/rchain#3450]
https://github.com/rchain/rchain/blob/b90040d0d35f23253e525f1792008df03fcb18dd/casper/src/main/resources/Registry.rho#L283-L294

In line 285, the suffix value would be taken ou. If the `update` doesn't put any new values inside, there would be nothing inside.

### What did you expect to see?
Expect to see the original value in treeHashMap even if  update failed.

### What did you see instead?

All the suffix values are missing.

### Steps to reproduce the bug

Deploy the rholang terms in the sequence.

1. initialize a treeHashMap and insert `Key: "a"`

```rholang
new
  rl(`rho:registry:lookup`),
  TreeHashMapCh,
  treeMapStore
  in {
  rl!(`rho:lang:treeHashMap`, *TreeHashMapCh) |
  for (TreeHashMap <- TreeHashMapCh){
    TreeHashMap!("init", 0, *treeMapStore) |
    for (@treeMap <-  treeMapStore){
      new a in {TreeHashMap!("set", treeMap, "a", "b", *a)}
      // store the treeHashMap handle in a public name which would be easier to retrieve
      |@"treeHashChannel"!(treeMap)
    }
  }
}
```

2. use the "update" method in treeHashMap

```
new
  rl(`rho:registry:lookup`),
  TreeHashMapCh
  in {
  rl!(`rho:lang:treeHashMap`, *TreeHashMapCh) |
  for (TreeHashMap <- TreeHashMapCh){
    for (@treeMap <<- @"treeHashChannel"){
      new a, updateFuncDoNothing in {
        TreeHashMap!("update", treeMap, "a", *updateFuncDoNothing, *a)
        }
    }
  }
}
```

3. read the treeHashMap from key "a" and find no value.

```
new TreeHashMapCh,rl(`rho:registry:lookup`),stdout(`rho:io:stdout`) in {
  rl!(`rho:lang:treeHashMap`, *TreeHashMapCh) |
  for (TreeHashMap <- TreeHashMapCh){
      for (@result<- @"treeHashChannel"){
        TreeHashMap!("get", result, "a", *stdout)
      }
  }
}
```

**Comment by tgrospic** [comment]
I'd say this is not a bug in TreeHashMap but in user code which does not updates the value.

But it seems that update can be dangerous in a sense that can block access to a key.

**Comment by zsluedem** [comment]
After discussing with @tgrospic 

The fact is that
The `update` API is designed to block other operation(including reading and set) on the same tree node to ensure the atomic operation.

The user must be careful how to use update here.

Another solution is that
```rholang
 new resultCh in { 
   for (@val <<- @[node, *storeToken]) { 
     // Update the current value 
     update!(val.get(suffix), *resultCh) | 
     for (@newVal <- resultCh) { 
       // Acquire the lock on this node  
       for (@val <- @[node, *storeToken]){
         @[node, *storeToken]!(val.set(suffix, newVal)) | 
         // Return 
         ret!(Nil) 
       }
     } 
   } 
```

Peek first and update the value after getting the updated value. The disadvantage of this is that if two parallel updates happened at the same time, the updated data can not be consistent.

Maybe we can add `unsafeUpdate` api like `fastUnsafeGet` here.
