### ISSUE TITLE
Conflict detection and state merging should include system deploy

### ISSUE THREAD

**Issue by zsluedem** [rchain/rchain#3456]
## Overview

Currently the conflict detection and state merging is not considering system deploy([closeBlock deploy and slashing deploy](https://github.com/rchain/rchain/blob/43257ddb7b2b53cffb59a5fe1d4c8296c18b8292/models/src/main/protobuf/CasperMessage.proto#L163-L168)).

The precharge and refund system deploy are included in user deploy event logs. So they are well considered.

We should consider the conflicts and merging in system deploy([closeBlock deploy and slashing deploy](https://github.com/rchain/rchain/blob/43257ddb7b2b53cffb59a5fe1d4c8296c18b8292/models/src/main/protobuf/CasperMessage.proto#L163-L168)).

### Impact

Same impact as hard fork 2

### Steps for integration testing

We need integration tests for epoch change in leaderful network.
https://github.com/rchain/rchain/pull/3457

**Comment by nzpr** [comment]
Not only conflict detection, but merging as well?

**Comment by zsluedem** [comment]
> Not only conflict detection, but merging as well?

yes. You are right
