### ISSUE TITLE
Change the format of wallets.txt file necessary for Hard Fork 1

### ISSUE THREAD

**Issue by tgrospic** [rchain/rchain#3460]
## Overview

Current format of `wallets.txt` file used for initial REV balance on genesis is using ETH address format. That was necessary for transfer of RHOC from Ethereum network to start with REV on RChain network.

ETH addresses are not used anymore so `wallets.txt` file should accept REV address format.

Line format should be:
```
<REV address 1>,<balance>
<REV address 2>,<balance>
```

Third parameter for the type of address (private key, contract) is not relevant anymore. And also for REV addresses we cannot find this information from address itself.

### Impact

`wallets.txt` file is used only for creation of a genesis block for fresh network so there is no impact on existing network.

**Comment by zsluedem** [comment]
@tgrospic We haven't finished this one, right?

**Comment by tgrospic** [comment]
Yes, first PR is just for preparation to REV address format in wallets file.

**Comment by tgrospic** [comment]
Bors didn't close the issue with batch merging.
