### ISSUE TITLE
Cleanup HotStore in-memory implementation

### ISSUE THREAD

**Issue by tgrospic** [rchain/rchain#3553]
## Overview

HotStore is fixed for race condition causing hash mismatch error in PR #3526. Part of the code can be simplified and be written in more functional style.

## Cleanup HotStore and related tests

- [x] Remove unnecessary parentheses and braces
  - when using higher-order functions (functions as arguments)
    e.g. `f(x => {...})` -> `f { x => ...}`
  - when functions return F values
  - wrapping single values
- [x] Remove custom `zip` functions for Map (used only in HotStore)
 https://github.com/rchain/rchain/blob/b66a704886bd96249fc2db115377f3e5dde6bc2a/rspace/src/main/scala/coop/rchain/rspace/HotStore.scala#L311
- [x] Use functions instead of manually destructuring (getOrElse, map, ...)
- [x] Create intermediate variables for long expressions
- [x] Create intermediate type aliases for long expressions
- [x] Use `apply` definition for HotStore (smart) constructors
- [x] Rewrite HotStoreState smart constructor with all default arguments
  - update HotStoreSpec to only specify non default arguments
- [x] Replace Ref.of with short version in HotStoreSpec, ReplayRSpaceTests, StorageTestsBase
  `Ref.of[Task, HotStoreState[C, P, A, K]]` => `Ref[Task].of`
- [x] HotStoreSpec
    - remove additional parameter `M[_]`
    - make Ref parameter in class History explicit
- [x] After finishing all refactorings, use long running test to verify hash mismatch error (@zsluedem)

**Comment by stanislavlyalin** [comment]
@tgrospic, please explain what do you mean `Remove unnecessary parentheses and braces...when functions return F values...wrapping single values`? Can you provide an examples? (probably outdated after fixing IDE warnings. Please see [linked PR](https://github.com/rchain/rchain/pull/3557)).

> Remove custom zip functions for Map (used only in HotStore)

Do you mean to remove using `zip` function?

> Use functions instead of manually destructuring (getOrElse, map, ...)

Little bit more explanation please

**Comment by tgrospic** [comment]
> Remove unnecessary parentheses and braces...when functions return F values

When we have functions defined like this:
```scala
def snapshot(): F[Snapshot[C, P, A, K]] = cacheRef.get.map(_.snapshot())
```
it can be rewritten as:
```scala
def snapshot: F[Snapshot[C, P, A, K]] = cacheRef.get.map(_.snapshot())
```
because F[_] is treated as value and it will be evaluated _lazily_.

> Do you mean to remove using zip function?

Yes, it can be rewritten with functions already defined on a Map and with the same amount of code.

> Use functions instead of manually destructuring (getOrElse, map, ...)

Instead of case analysis on the underlying type (knowing and have access to constructors) we want whenever is possible to use defined functions which do the same.
```scala
val a: Option[Int] = Some(42)

// Matching manually
val b = a match {
  case Some(n) => s"Have $n!"
  case None    => "No value here!"
}
// Using Functor to transform and return default
val b = a.map(n => s"Have $n!").getOrElse("No value here!")
```
