### ISSUE TITLE
Create pubKey configuration for POS multi-sig wallet

### ISSUE THREAD

**Issue by zsluedem** [rchain/rchain#3625]
## Overview

Proof of Stake contract has hard-coded value for multi-sig vault used for slashed stake. Instead of hard-coded public keys and quorum size they should be supplied as configuration parameters when genesis block is created. 

Currently rnode use [pureconfig](https://pureconfig.github.io/docs/index.html) to read config.

Pureconfig support `HOCON`, json, java`.properties` format. They all support array config.

#### Example
HOCON
```
pubKeys = [
   pubKey1, pubKey2, pubKey3
]
```

Json
```
{"pubKeys":[pubKey1, pubKey2, pubKey3]}
```

[Jave .properties](https://help.mulesoft.com/s/question/0D52T00004mXUpxSAG/how-to-declare-array-in-properties-file)(Doesn't care actually, no one uses this)

### Design

We should introduce this config like [bond-maximum](https://github.com/rchain/rchain/blob/dev/node/src/main/resources/defaults.conf#L270) which would be rendered in the [POS contract](https://github.com/rchain/rchain/blob/dev/casper/src/main/scala/coop/rchain/casper/genesis/contracts/ProofOfStake.scala#L10-L32)

- [x] Introduce POS multi-sig pub keys (pos-multi-sig-public-keys) in https://github.com/rchain/rchain/blob/dev/node/src/main/resources/defaults.conf#L250-L290
- [x] Pass these `pubKeys` configs in https://github.com/rchain/rchain/blob/dev/casper/src/main/scala/coop/rchain/casper/genesis/contracts/ProofOfStake.scala#L10-L32
- [x] Introduce `posMultiSigQuorum` (pos-multi-sig-quorum) as a config parameter which defines how many confirmations are necessary to use multi-sig vault
  - this number should be checked to be less or equal the number of supplied public keys
- [x] Replace the hard-coded https://github.com/rchain/rchain/blob/888c8040892/casper/src/main/resources/PoS.rhox#L110-L112 pub keys and quorum data into parsing config with `$$` like https://github.com/rchain/rchain/blob/888c8040892/casper/src/main/resources/PoS.rhox#L240
- [ ] Add CLI options, it seems that rogach has support for lists e.g. --pub abc def.
  https://github.com/scallop/scallop/wiki/Option-types-and-definitions#trailing-arguments

### Verification

1. Start fresh node with 2 public keys for PoS multi-sig vault and quorum 1
2. Run exploratory deploy to get multi-sig REV address
    ```scala
    new return, lookup(`rho:registry:lookup`) in {
      new posCh, multiSigVaultCh in {
        lookup!(`rho:rchain:pos`, *posCh) |
        for(@(_, pos) <- posCh) {
          @pos!("getCoopVault", *multiSigVaultCh) |
          for(@(_, revAaddress, _) <- multiSigVaultCh) {
            return!(revAaddress)
          }
        }
      }
    }
    ```
3. Transfer 100 REVs to multi-sig REV address
    - needed to transfer REVs from multi-sig
5. Transfer 100 REVs to the first multi-sig public key (REV address)
    - needed to pay for deploy
6. Create deploy to transfer from multi-sig address to any other address and check that transfer is successful
    - variables are `${toAddr}` for target address (String) and `${amount}` (Number)
    ```scala
      new out(\`rho:io:stdout\`)
        , deployId(\`rho:rchain:deployId\`), deployerId(\`rho:rchain:deployerId\`)
        , lookup(\`rho:registry:lookup\`)
        , posCh, msRevVaultCh, revVaultCh, posMultiSigVaultCh, deployerKeyCh, toRevVaultCh, transferRetCh
      in {
        lookup!(\`rho:rchain:pos\`, *posCh) |
        lookup!(\`rho:rchain:multiSigRevVault\`, *msRevVaultCh) |
        lookup!(\`rho:rchain:revVault\`, *revVaultCh) |
        for(@(_, Pos) <- posCh ; @(_, MultiSigVault) <- msRevVaultCh ; @(_, RevVault) <- revVaultCh) {
          @Pos!("getCoopVault", *posMultiSigVaultCh) |
          @MultiSigVault!("deployerAuthKey", *deployerId, *deployerKeyCh) |
          @RevVault!("findOrCreate", "${toAddr}", *toRevVaultCh) |
          for(@(msRevVault, msRevAaddress, _) <- posMultiSigVaultCh ; _ <- toRevVaultCh ; @deployerKey <- deployerKeyCh) {
            @msRevVault!("transfer", "${toAddr}", ${amount}, deployerKey, *transferRetCh) |
            for(@transferRet <- transferRetCh) {
              deployId!(("Transfer result", transferRet))
            }
          }
        }
      }
    ```

**Comment by stanislavlyalin** [comment]
> Introduce posMultiSigQuorum (pos-multi-sig-quorum) as a config parameter which defines how many confirmations are necessary to use multi-sig vault

@tgrospic, can you provide please where this parameter is used in [PoS.rhox](https://github.com/rchain/rchain/blob/3371c8a400f4b82a7af833f25b9a0b6fc71709db/casper/src/main/resources/PoS.rhox) and what is default value?

How to check the changes in this file works correctly?

**Comment by zsluedem** [comment]
> @tgrospic, can you provide please where this parameter is used in [PoS.rhox](https://github.com/rchain/rchain/blob/3371c8a400f4b82a7af833f25b9a0b6fc71709db/casper/src/main/resources/PoS.rhox) and what is default value?

It is in the `4` item of `Design`.

**Comment by stanislavlyalin** [comment]
In the 4 item of design described just public keys, not quorum.

**Comment by tgrospic** [comment]
This is the whole configuration of multi-sig vault. Two array arguments are public keys and unforgeable names and after that is the number which represents the quorum size.
https://github.com/rchain/rchain/blob/3371c8a400f4b82a7af833f25b9a0b6fc71709db/casper/src/main/resources/PoS.rhox#L81-L91

**Comment by tgrospic** [comment]
CLI options are not added. Description is updated with the info how to use lists options.
