### ISSUE TITLE
Add shard ID to deploy data

### ISSUE THREAD

**Issue by tgrospic** [rchain/rchain#3628]
## Overview

To prevent replay of deploys between shards we need to add shard identifier to deploy data signed by the deployer.

**NOTE: This change is incompatible with the validator block creation/validation and client libraries/dApps which are using deploys.**

https://github.com/rchain/rchain/blob/93d8907f28506b87306bb16c296d496cd9fe6c7b/models/src/main/protobuf/CasperMessage.proto#L139-L148

## Releases

This feature should be first applied to as an patch to `v0.12.5` used by RPC and later added as part of `v0.13.x` version. Existing client libraries (wallets) must be taken into consideration.

Also we need to decide how we want to roll out this change in regard to current main net. Should we continue with existing deploy data structure until Hard Fork 2 or apply it immediately.

## Solution

The new `shardId` field in DeployData type should be validated when deploy is submitted to the node and also when block is replayed.
`shardId` must be signed together with existing fields signed fields in DeployData type.

Validation of shardId should be done in BlockAPI and block validation.

https://github.com/rchain/rchain/blob/0367c41a2b2645ad4ec6d8faaed7d7486870f175/casper/src/main/scala/coop/rchain/casper/api/BlockAPI.scala#L53-L105

In block validation shardId validation should be moved before `repeatDeploy` and before deploys shardId validation.

https://github.com/rchain/rchain/blob/45b83dfe614f30e4705fc1649a6266da3f4f9e95/casper/src/main/scala/coop/rchain/casper/Validate.scala#L160-L190

- [x] Create feature branch `feature/v0.12-rpc` based on `v0.12.5` tag to track special release for RPC
  https://github.com/rchain/rchain/tree/feature/v0.12-rpc
- [x] Create PR to `dev` branch to be ready for `0.13.x` version
  https://github.com/rchain/rchain/pull/3631
- [x] Create PR to `feature/v0.12-rpc` branch
  https://github.com/rchain/rchain/pull/3645

**Comment by zsluedem** [comment]
Please add rholang version number for future change, too.

**Comment by tgrospic** [comment]
> Please add rholang version number for future change, too.

@zsluedem Please provide more information how this version will be used.

**Comment by stanislavlyalin** [comment]
@tgrospic, is the solution require only adding the field to `DeployDataProto` and updating client libs (pyrchain) or in `DeployData` also and all related changes? Should checking shard ID in replay also be implemented?

**Comment by tgrospic** [comment]
@stanislavlyalin I've updated the description. Yes, shardId must be verified.

**Comment by zsluedem** [comment]
> > Please add rholang version number for future change, too.
> 
> @zsluedem Please provide more information how this version will be used.

@tgrospic Oh. Sorry. After some thoughts, I think maybe it make more sense we add it when it is needed.
