### ISSUE TITLE
Refactor BlockAPI

### ISSUE THREAD

**Issue by tgrospic** [rchain/rchain#3659]
## Overview

To include new multi-parent finalization we need to refactor/delete a lot of existing code.

As part of this change we need to simplify current `BlockAPI` implementation.

## Design

1. Create `BlockAPI` trait with existing methods currently defined on the BlockAPI object
    - for now it can be in models project (because we have generated protobuf there!) in `coop.rchain.api`
1. Create implementation which should only accept RuntimeManager and BlockDagStorage (BlockDagRepresentation)
    - for all other dependencies just add TODO comment with fake data
1. Instantiate new BlockAPI implementation in `Setup` and use where is needed like gRPC servers and WebAPI

## Additional changes

Currently, `addDeploy` method is defined on MultiParentCasperImpl which is used in BlockAPI. This should be moved directly to new BlockAPI implementation and DeloyStorage should be accessible in BlockDagStorage.

**Comment by nzpr** [comment]
Had https://github.com/rchain/rchain/pull/3662 closed this?

**Comment by stanislavlyalin** [comment]
> Had #3662 closed this?

The third point has not yet been implemented
