### ISSUE TITLE
Refactoring of History and RadixTree data types

### ISSUE THREAD

**Issue by hilltracer** [rchain/rchain#3670]
## Overview
For better readability and code organization, we need to use common history types in these data structures:
https://github.com/rchain/rchain/blob/04bc32552441531fa49dc7e78e03039b1550e9ce/rspace/src/main/scala/coop/rchain/rspace/history/RadixTree.scala#L25-L33

### Impact
Many files are in Rspace because `KeyPath` is used in many places.

### Steps to implement the solution
1. Fully remove old implementation of History (also tests, and related files).
https://github.com/rchain/rchain/blob/04bc32552441531fa49dc7e78e03039b1550e9ce/rspace/src/main/scala/coop/rchain/rspace/history/HistoryMergingInstances.scala#L47-L51
1. Change `value: ByteVector` and `ptr: ByteVector` to `value: Blake2b256Hash` and `ptr: Blake2b256Hash`. Adaptation RadixTree code for new data types.
1. Create trait `KeyPath`. This trait should be founded on ByteVector. Need to create basic operations: append, equal, common, ... etc. Change `prefix: ByteVector` to `prefix: KeyPath` in RadixTree, adapt RadixTree code.
1. Use a new type in history instead of this data type:
https://github.com/rchain/rchain/blob/04bc32552441531fa49dc7e78e03039b1550e9ce/rspace/src/main/scala/coop/rchain/rspace/history/History.scala#L80
Adopting history implementation and these data types for the new KeyPath:
https://github.com/rchain/rchain/blob/04bc32552441531fa49dc7e78e03039b1550e9ce/rspace/src/main/scala/coop/rchain/rspace/history/HistoryAction.scala#L10-L11

### Steps for integration testing
After each step needed to validate, that time performance doesn't slower than the old implementation. With the help [tests](https://github.com/rchain/rchain/blob/04bc32552441531fa49dc7e78e03039b1550e9ce/node/src/test/scala/coop/rchain/node/perf/HistoryGenKeySpec.scala). Need to increase the size of data to 100000 records in tests temporally.

**Comment by hilltracer** [comment]
@tgrospic I don't know how it will be better. Maybe instead of using  `Blake2b256Hash` directly, we should create `trait HashPath`  founded on `Blake2b256Hash`? But in this case, we should change many files in Rspace, because `Blake2b256Hash` is used in all places.

**Comment by hilltracer** [comment]
Also, I can't assign this issue to Maxim (`maximus19910112`), he isn't on this list:
![image](https://user-images.githubusercontent.com/81892279/165060746-a7b90c93-aa6b-44e0-8e2d-a168f7304f60.png)

**Comment by hilltracer** [comment]
@tgrospic where will be better write new implementation of `HashPath`? It can be [history.scala](https://github.com/rchain/rchain/blob/04bc32552441531fa49dc7e78e03039b1550e9ce/rspace/src/main/scala/coop/rchain/rspace/history/History.scala). Or maybe better to create new file in this dir?

**Comment by tgrospic** [comment]
Let's first go with `Blake2b256Hash`. We will need to abstract over hashing algorithm anyway if we want to move to Blake3.

**Comment by hilltracer** [comment]
> @tgrospic where will be better write new implementation of `HashPath`? It can be [history.scala](https://github.com/rchain/rchain/blob/04bc32552441531fa49dc7e78e03039b1550e9ce/rspace/src/main/scala/coop/rchain/rspace/history/History.scala). Or maybe better to create new file in this dir?

@tgrospic We have similar ques about location `KeyPath`.

**Comment by tgrospic** [comment]
> > @tgrospic where will be better write new implementation of `HashPath`? It can be [history.scala](https://github.com/rchain/rchain/blob/04bc32552441531fa49dc7e78e03039b1550e9ce/rspace/src/main/scala/coop/rchain/rspace/history/History.scala). Or maybe better to create new file in this dir?
> 
> @tgrospic We have similar ques about location `KeyPath`.

I've added comments to @maximus19910112  PR #3674.

**Comment by tgrospic** [comment]
@hilltracer Is this issue completed?

**Comment by hilltracer** [comment]
Yes, it is. In the future we can create a new issue for refactoring: 
```scala
  type Node = Vector[Item]
```
https://github.com/maximus19910112/rchain/blob/e50c7d881a02a21774cd75a936115d28c7712b38/rspace/src/main/scala/coop/rchain/rspace/history/RadixTree.scala#L45
