### ISSUE TITLE
Removing unused unforgeable name predicting tools and api

### ISSUE THREAD

**Issue by zsluedem** [rchain/rchain#3690]
## Overview

After #3687 , the user who want to use `InsertSigned` would not need an explicit signature in the rholang term anymore.

### Impact

Users who is using `/api/prepare-deploy` should change their codes.

### Design

1. https://github.com/rchain/rchain/blob/4f94bf706a6943c055b95e65609f8cc3073eea33/casper/src/main/scala/coop/rchain/casper/rholang/RegistrySigGen.scala
This file could be totally removed because it is used to generate the signature of the `InsertSigned`. The generated contents are in https://github.com/rchain/rchain/blob/4f94bf706a6943c055b95e65609f8cc3073eea33/casper/src/main/resources/AuthKey.rho#L1-L16

2. :heavy_check_mark: The `/api/prepare-deploy` is not longer userful once [we change how random seed comes from](https://github.com/rchain-test/rchain-secure/issues/3). We should remove this api and the related codes. https://github.com/rchain/rchain/blob/4f94bf706a6943c055b95e65609f8cc3073eea33/node/src/main/scala/coop/rchain/node/api/WebApi.scala#L74-L88 should be removed and https://github.com/rchain/rchain/blob/4f94bf706a6943c055b95e65609f8cc3073eea33/casper/src/main/scala/coop/rchain/casper/api/BlockApiImpl.scala#L515-L524 should be removed

3. :heavy_check_mark: remove the related grpc definitions https://github.com/rchain/rchain/blob/2399df3fe7a996bb53de2c9174b6f5feae73b167/models/src/main/protobuf/DeployServiceV1.proto#L53-L54 and https://github.com/rchain/rchain/blob/2399df3fe7a996bb53de2c9174b6f5feae73b167/models/src/main/protobuf/DeployServiceCommon.proto#L74-L78 and the related api https://github.com/rchain/rchain/blob/2399df3fe7a996bb53de2c9174b6f5feae73b167/node/src/main/scala/coop/rchain/node/api/DeployGrpcServiceV1.scala#L179-L189

### Resource estimation

One day

**Comment by tgrospic** [comment]
@zsluedem Please add info about protobuf files update.

**Comment by tgrospic** [comment]
@stanislavlyalin Is there something left to do on this issue, when you re-open it?

**Comment by stanislavlyalin** [comment]
> @stanislavlyalin Is there something left to do on this issue, when you re-open it?

My PR covers just 2nd and 3rd parts of issue.

**Comment by tgrospic** [comment]
@maximus19910112 Please take the task of the first item to remove RegistrySigGen.scala file.
