### ISSUE TITLE
Remove host check when node starts

### ISSUE THREAD

**Issue by tgrospic** [rchain/rchain#3707]
## Overview

Currently, node have a check for valid host when starts. Also there is parameter to `--allow-private-addresses` to allow binding to a local host. 
Both of these doesn't make sense. Host can legitimate be not accessible inside the server where node is running and having additional option for local hosts just makes configuration more difficult.

More information why this is also a problem can be found on this issue.
- #3518

Why is meaningless to check valid host when node starts is because anyone can modify node behavior and set any host in node address as it likes. **Check of valid host should be on the receiver side when node receives request from peers to connect, to prevent local loopback to invalid hosts.**

## Solution

For now we need to remove host checking completely and remove `--allow-private-addresses` config parameter.
https://github.com/rchain/rchain/blob/370eee8f8227f6b8c93892d6a300bcc59f5b7e65/node/src/main/scala/coop/rchain/node/Main.scala#L89

NOTE: keep `--allow-private-addresses` CLI option but print warning to the log that this option is not used anymore and will be removed in future versions, to minimize breaking changes for users which are now forced to use it, like VSCode extension.

- [x] Remove host check when node starts
  #3734
- [x] Implement host check for peers to prevent mixing of public/private subnets
  #3761
  This can pose security risk if public nodes accept local subnets. In that way public nodes can try to probe local networks of connected peers.

### References

- #2474
- https://rchain.atlassian.net/browse/RCHAIN-3435

**Comment by nzpr** [comment]
This is where node answers to request to establish p2p connection. 
https://github.com/rchain/rchain/blob/0ad4974f751f1be0a7d706dc07ff7a635041716c/comm/src/main/scala/coop/rchain/comm/rp/HandleMessages.scala#L76-L91
We only want to accept connections from peers that can be accessed.
Here the existing check can be performed (double check is required to understand what are the blacklisted addresses there now)
https://github.com/rchain/rchain/blob/0c35dad7802a62c2a0ea55857cf53f7adc121094/comm/src/main/scala/coop/rchain/comm/package.scala#L27
OR, maybe what is better - we can perform some kind of a check for remote node, e.g. just ping and see if remote address is reachable. Also we can read the status API and e.g. look if the version of the remote node is compatible, and reject connection if it is not.

**Comment by tgrospic** [comment]
I agree for version checking, but for that some kind of version compatibility strategy must be built which can take into account major, minor, patches version difference.

Maybe for now simple check can suffice. If node host is local allow local peers, and if internet allow only internet peers. Do you see any situation which this will not work?

**Comment by nzpr** [comment]
I think we can just check if protocol and discovery ports are reachable and thats it. We don't care whats the address, we only care that the address that peer offers is reachable. So if peer tells that `I'm 0.0.0.0?protocol=40400&discovery=40404`, we check ports, if they are not available - discard the handshake, if they are - add to the table

**Comment by nzpr** [comment]
Hm, I'm thinking that there can be multiple nodes with `rnode://<key>?0.0.0.0?protocol=40400&discovery=40404`
Node A and node B have on their local machines nodes that are not visible to outsiders. But these nodes will be broadcasted via kademlia.

So I think the logic should be:
Once node receive handshake from `rnode://$sKey@${endpoint.host}?protocol=${endpoint.tcpPort}&discovery=${endpoint.udpPort}`
1) check if protocol and discovery ports are reachable
2) check that node `sKey` is really one that is inside handshake. Otherwise this might be some other peer from another node which is not available to handshake recipient
3) add peer if 1 and 2 are ok

I'm not sure though check 2 is feasible using the protocol port, or this data is available only via API port .

**Comment by tgrospic** [comment]
Maybe we don't want to extend this task to much because it requires some experimentation how to correctly detect accessible peers. I think the main problem from where we started is to prevent local or loopback addresses to be sent from internet nodes. If node is connected to the internet we don't want to blindly add local peers which cannot be visible from internet peers although reachable from node itself.
