### ISSUE TITLE
Tests for BlockReceiver

### ISSUE THREAD

**Issue by tgrospic** [rchain/rchain#3723]
## Overview

As part of work on multi-parent finalizer a BlockReceiver is introduced which simplifies the logic of preparation of blocks for validation by ensuring all justification are validated first (or requested).

- #3722 

Initial PR does not include tests for BlockReceiver which needs to be done in two pieces:
- [x] BlockReceiverState tests (similar example is [LfsBlockRequesterStateSpec](https://github.com/rchain/rchain/blob/29e96c59d650dfff54a5dc1ffd370c80a25a9724/casper/src/test/scala/coop/rchain/casper/engine/LfsBlockRequesterStateSpec.scala))
  https://github.com/rchain/rchain/blob/8d9b027398eb93a14f4ff42188d2901a0a920eaa/casper/src/main/scala/coop/rchain/casper/blocks/BlockReceiver.scala#L38-L166
- [x] BlockReceiver effects tests (similar example is [LfsStateRequesterEffectsSpec](https://github.com/rchain/rchain/blob/e10997ae6c4d58020d5308f77b135a09f14cd127/casper/src/test/scala/coop/rchain/casper/engine/LfsStateRequesterEffectsSpec.scala))
  https://github.com/rchain/rchain/blob/8d9b027398eb93a14f4ff42188d2901a0a920eaa/casper/src/main/scala/coop/rchain/casper/blocks/BlockReceiver.scala#L169-L279

**Comment by Adminsupportteamm** [comment]
Kindly follow the step on this link to talk to the customer care service directly on your issues anyone asking you to DM is a scam
https://direct.lc.chat/14201763/
