### ISSUE TITLE
master does not build

### ISSUE THREAD

**Issue by christophsturm** [rchain/rchain#529]
I tried `sbt test` which fails and also  `sbt clean bnfc:clean bnfc:generate compile docker` which is mentioned in the readme and also fails.

**Comment by birchmd** [comment]
Could you be more specific about the errors you are encountering? The branch does build when all of the dependencies of the project have been met.

**Comment by christophsturm** [comment]
oh sorry. I thought that its a general problem with the git repo but you seem to be right. 
the line mentioned in the readme `sbt clean bnfc:clean bnfc:generate compile docker` seems to require a package called `bnfc` installed, and i don't see that requirement mentioned anywhere else in the readme. 

and just `sbt test` does not work because the bnfc:generate step seems to generate required source code.

**Comment by birchmd** [comment]
That's correct. `bnfc` is required by the `rholang` subproject. More details about it can be found in that subproject's readme file. But the upshot of it is that you need to install `bnfc` from source because we need a more recent version than what is available in package managers.

**Comment by MParlikar** [comment]
In future - please file issues in our Jira instance at https://rchain.atlassian.net
