### ISSUE TITLE
multiple versions of sbt: 0.13.16 in comm, 0.13.11 in rholang

### ISSUE THREAD

**Issue by dckc** [rchain/rchain#55]
Is this important? It slows down builds.

**Comment by MParlikar** [comment]
Yes it is important.  We will pick 1 version and document it.  Thank you

**Comment by DoSOfRedRiver** [comment]
I guess we should move towards to sbt 1.x, but it should take some time to test build with new sbt version.

**Comment by dckc** [comment]
sbt 1.x is known to not work. I tried it and failed; Chris told me it's too new. I don't see any particular benefit to moving to 1.x.

But please do try to build rholang with 0.13.16. Maybe I'll find time to try it.

**Comment by dckc** [comment]
I suppose sbt is "the devil you know" but this [So, what's wrong with SBT?](http://www.lihaoyi.com/post/SowhatswrongwithSBT.html) rings true to me.

I wonder if gradle would be substantially less horrible.

**Comment by dckc** [comment]
oh... I see gradle offers nothing like `sbt console`. Bzzt.

**Comment by dckc** [comment]
in PR #60, this seems to work:
 - 64d0ede uniform sbt version: 0.13.16

**Comment by dckc** [comment]
Fixed in #60
