### ISSUE TITLE
5 different scala versions?!?!?!

### ISSUE THREAD

**Issue by dckc** [rchain/rchain#57]
rchain/comm
[info] 'compiler-interface' not yet compiled for Scala 2.12.3. Compiling...

rchain/rholang
[info] 'compiler-interface' not yet compiled for Scala 2.10.6. Compiling...

rchain/rholang
[info] 'compiler-interface' not yet compiled for Scala 2.11.8. Compiling...

rchain/roscala
[info] 'compiler-interface' not yet compiled for Scala 2.10.6. Compiling...

rchain/storage
[info] 'compiler-interface' not yet compiled for Scala 2.12.1. Compiling...

https://travis-ci.org/rchain/rchain/builds/305097535?utm_source=github_status&utm_medium=notification

**Comment by dckc** [comment]
In PR #60, this seems to work:
 - e441157 storage: scalaVersion 2.12.3 to match comm etc.
 - 2462d64 rholang: scalaVersion 2.12.3 to match comm etc.  …

**Comment by griff-pyrofex** [comment]
None of my code should depend on a specific version of the compiler.  Change it to whatever is convenient.

**Comment by dckc** [comment]
Fixed by #60
