### ISSUE TITLE
not found: type RChainException in storage

### ISSUE THREAD

**Issue by dckc** [rchain/rchain#58]
```
[info] Compiling 5 Scala sources to /home/travis/build/rchain/rchain/storage/target/scala-2.12/classes...
[info] 'compiler-interface' not yet compiled for Scala 2.12.1. Compiling...
[info]   Compilation completed in 19.477 s
[error] /home/travis/build/rchain/rchain/storage/src/main/scala/coop/rchain/storage/Key.scala:21: not found: type RChainException
[error]     throw new RChainException("Key constructor got null or empty parameter")
```

etc.

**Comment by tymm** [comment]
@DoSOfRedRiver is working on fixing CI.
@griff-pyrofex seems like you forgot to add the file which contains `RChainException`? Also `Storage` is missing.

**Comment by griff-pyrofex** [comment]
When I look in the dev branch of storage, https://github.com/rchain/rchain/tree/dev/storage/src/main/scala/coop/rchain/storage, I see all seven of the scala files I expect.  I’ve attached a screenshot.

The class RChainException is defined in src/main/scala/coop/rchain/storage/Lmdb.scala, which is present, as far as I can tell.

I have also attached a trace of me cloning, building, and running the code without errors.

Any suggestions are appreciated, thanks.
![storage_dev_griff_2017-11-22](https://user-images.githubusercontent.com/30306929/33151189-426a92e6-cf94-11e7-8fe4-829a0f447021.png)
[storage_builds_griff_2017-11-22.txt](https://github.com/rchain/rchain/files/1497557/storage_builds_griff_2017-11-22.txt)

**Comment by dckc** [comment]
When I compare your log to the raw log from [build 8](https://travis-ci.org/rchain/rchain/builds/305097535?utm_source=github_status&utm_medium=notification), the first thing I notice is your says `Getting org.scala-sbt sbt 1.0.3` where build 8 says `Getting org.scala-sbt sbt 0.13.9`.

Yours says `Compiling 12 Scala sources` where build 8 says `Compiling 5 Scala sources`.

Very odd...

**Comment by MParlikar** [comment]
When I have hit this issue in the past (read- distant past) - I have found
that starting with a completely fresh 'get' or 'clone' of the repo in a
fresh environment will expose the issue.  In almost every instance when I
have hit this issue, I have missed a dependency or missed committing a file
to the repository.

I would strongly advise going that route, to make sure that all the right
stuff has been pushed to the repo.

Medha

**Comment by dckc** [comment]
Grif's screenshot shows cd3964f; my work started from Kent's 21be575; their common ancestor is 83a9a9a from Nov 8, which is missing quite a bit of Grif's work. I think that's what's going on.

**Comment by MParlikar** [comment]
Great - give it a shot from the right start point and let me know.  thanks!

**Comment by dckc** [comment]
Yup; after I rebased to a more current `dev` with Grif's work, all is well:

  - [build 9](https://travis-ci.org/rchain/rchain/builds/306052405)
