### ISSUE TITLE
The releases page has a dead link to a docker

### ISSUE THREAD

**Issue by greggdourgarian** [rchain/rchain#741]
https://github.com/rchain/rchain/releases has a dead link associated with the text below under the Node.hello pre-release notes.

"Docker image may be found here."

**Comment by KellyatPyrofex** [comment]
Thanks for the catch, @greggdourgarian! We will update the release page to remove the dead links. We recommend users pull the latest image of RNode with the command `docker pull rchain/rnode`. If you want to see previous images of earlier versions, they are shown at tagged versions on https://store.docker.com/community/images/rchain/rnode.
